<a href="https://colab.research.google.com/github/the-headliner/Battle_ship/blob/main/Copy_of_MinEditDistance_Autocorrect_LK_W1_C2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 1: Autocorrect

Welcome to the first assignment of Course 2. This assignment will give you a chance to brush up on your python and probability skills. In doing so, you will implement an auto-correct system that is very effective and useful.

Before starting make sure that you are following the following assignment instructions

## Assignment Instructions
Create a Copy in Your Google Drive:
* Before you begin working on this assignment, you must create a copy of this Colab file in your own Google Drive.
* To do this, go to the menu bar at the top of this page, click on File > Save a copy in Drive.... This will save a copy of this file in your Google Drive under the name Copy of <Original File Name>. Rename the file.
* Ensure you are logged into your msitprogram.net account when doing this.

Work on Your Copy:
* Do not edit this original file.
* All your work must be done on the copy saved in your Google Drive. Any work done on this original file will not be saved and may be lost.

Saving Your Work:
* Google Colab automatically saves your progress in the copy stored in your Drive. However, it's a good practice to manually save your work periodically by clicking on File > Save.


Let's get started!!!

## Table of Contents
- [0 - Overview](#0)
    - [0.1 - Edit Distance](#0-1)
- [1 - Data Preprocessing](#1)
    - [Exercise 1 - process_data](#ex-1)
    - [Exercise 2 - get_count](#ex-2)
    - [Exercise 3 - get_probs](#ex-3)
- [2 - String Manipulations](#2)
    - [Exercise 4 - delete_letter](#ex-4)
    - [Exercise 5 - switch_letter](#ex-5)
    - [Exercise 6 - replace_letter](#ex-6)
    - [Exercise 7 - insert_letter](#ex-7)
- [3 - Combining the Edits](#3)
    - [3.1 - Edit One Letter](#3-1)
        - [Exercise 8 - edit_one_letter](#ex-8)
    - [3.2 - Edit Two Letters](#3-2)
        - [Exercise 9 - edit_two_letters](#ex-9)
    - [3.3 - Suggest Spelling Suggestions](#3-3)
        - [Exercise 10 - get_corrections](#ex-10)
- [4 - Minimum Edit Distance](#4)
    - [4.1 - Dynamic Programming](#4-1)
        - [Exercise 11 - min_edit_distance](#ex-11)
- [5 - Backtrace](#5)

<a name='0'></a>
## 0 - Overview

You use autocorrect every day on your cell phone and computer. In this assignment, you will explore what really goes on behind the scenes. Of course, the model you are about to implement is not identical to the one used in your phone, but it is still quite good.

By completing this assignment you will learn how to:

- Get a word count given a corpus
- Get a word probability in the corpus
- Manipulate strings
- Filter strings
- Implement Minimum edit distance to compare strings and to help find the optimal path for the edits.
- Understand how dynamic programming works


Similar systems are used everywhere.
- For example, if you type in the word **"I am lerningg"**, chances are very high that you meant to write **"learning"**, as shown in **Figure 1**.

![Figure 1](https://drive.google.com/uc?export=view&id=1Q9ZBcjPh8vgmQ8NOapSAXrcmZZ9QiUX7)

<a name='0-1'></a>
### 0.1 - Edit Distance

In this assignment, you will implement models that correct words that are 1 and 2 edit distances away.
- We say two words are n edit distance away from each other when we need n edits to change one word into another.

An edit could consist of one of the following options:

- Delete (remove a letter): ‘hat’ => ‘at, ha, ht’
- Switch (swap 2 adjacent letters): ‘eta’ => ‘eat, tea,...’
- Replace (change 1 letter to another): ‘jat’ => ‘hat, rat, cat, mat, ...’
- Insert (add a letter): ‘te’ => ‘the, ten, ate, ...’

You will be using the four methods above to implement an Auto-correct.
- To do so, you will need to compute probabilities that a certain word is correct given an input.

This auto-correct you are about to implement was first created by [Peter Norvig](https://en.wikipedia.org/wiki/Peter_Norvig) in 2007.
- His [original article](https://norvig.com/spell-correct.html) may be a useful reference for this assignment.

The goal of our spell check model is to compute the following probability:

$$P(c|w) = \frac{P(w|c)\times P(c)}{P(w)} \tag{Eqn-1}$$

The equation above is [Bayes Rule](https://en.wikipedia.org/wiki/Bayes%27_theorem).
- Equation 1 says that the probability of a word being correct $P(c|w) $is equal to the probability of having a certain word $w$, given that it is correct $P(w|c)$, multiplied by the probability of being correct in general $P(C)$ divided by the probability of that word $w$ appearing $P(w)$ in general.
- To compute equation 1, you will first import a data set and then create all the probabilities that you need using that data set.

<a name='1'></a>
## 1 - Data Preprocessing

In [ ]:
import re
import collections
from collections import Counter
import numpy as np
import pandas as pd

As in any other machine learning task, the first thing you have to do is process your data set.

In this assignment we will be using a data file called **'shakespeare.txt'**, which can be found at the following link: https://docs.google.com/document/d/1JkbbpLCyGEPQjHQfqpBrNrpMLac-ah9kOe6SK75K4I0/edit?usp=share_link

Download the file to your local system and then upload it to Google Colab by following the instructions below

### Connect to Your Local Runtime
If you haven’t connected to a local runtime yet, follow these steps:
1. Click on Connect in the top-right corner of the Google Colab interface.
2. Choose Connect to local runtime....
3. Follow the instructions to set up the local runtime.

### Open the Files Menu
1. On the left-hand side of your Google Colab notebook, you’ll see a vertical toolbar. Click on the folder icon to open the "Files" menu.
2. If the "Files" menu is not visible, you can open it by clicking on the three vertical dots in the toolbar and selecting Files.

### Upload Files
1. In the "Files" menu, click on the Upload button at the top (shaped like a file icon with an upward arrow).
2. A file selection dialog will appear. Browse your local file system and select the files you want to upload.
3. Once selected, the files will start uploading. You will see progress indicators next to each file as they upload.
4. After the upload is complete, the files will appear in the "Files" menu and will be available in your current working directory.

### Get the File Path
1. In the "Files" menu, right-click on the uploaded file.
2. Select Copy path from the context menu that appears.
3. The file path will be copied to your clipboard, and you can paste it directly into your code.

### Access Uploaded Files in Your Code
Now that you have the file path, you can access the file in your notebook. For example:

```python
import pandas as pd

# Use the copied file path to load the uploaded CSV file
df = pd.read_csv('/content/your_uploaded_file.csv')
print(df.head())
```
### Managing Files
You can also manage your files directly in the "Files" menu:
1. Create new folders: Right-click (or use the options menu) in the "Files" menu to create a new folder.
2. Delete files: Right-click on a file and select "Delete" to remove it from the environment.
3. Refresh: If you make changes to your files externally, you can click the refresh button in the "Files" menu to update the view.

### Additional Note:
Important: If the runtime resets (either due to a timeout, disconnection, or manual restart), all files uploaded through the "Files" menu will be lost, and you will need to upload them again.

<a name='ex-1'></a>
### Exercise 1 - process_data
Implement the function `process_data` which

1) Reads in a corpus (text file)

2) Changes everything to lowercase

3) Returns a list of words.

<details>    
<summary>
    <font size="3" color="darkgreen"><b>General Hints</b></font>
</summary>
<p>
    
General Hints to get started
<ul>
    <li>Python <a href="https://docs.python.org/3/tutorial/inputoutput.html">input and output<a></li>
    <li>Python <a href="https://docs.python.org/3/library/re.html" >'re' documentation </a> </li>
</ul>
</p>


<details>    
<summary>
    <font size="3" color="darkgreen"><b>Detailed Hints</b></font>
</summary>
<p>     
Detailed hints if you're stuck
<ul>
    <li>Use 'with' syntax to read a file</li>
    <li>Decide whether to use 'read()' or 'readline().  What's the difference?</li>
    <li>You can use str.lower() to convert to lowercase.</li>
    <li>Use re.findall(pattern, string)</li>
    <li>Look for the "Raw String Notation" section in the Python 're' documentation to understand the difference between r'\W', r'\W' and '\\W'. </li>
    <li>For the pattern, decide between using '\s', '\w', '\s+' or '\w+'.  What do you think are the differences?</li>
</ul>
</p>


In [ ]:
def process_data(file_name):
    """
    Input:
        A file_name which is found in your current directory. You just have to read it in.

    Output:
        words: a list containing all the words in the corpus (text file you read) in lower case.
    """
    words = [] # return this variable correctly

    ### START CODE HERE ###

    #Open the file, read its contents into a string variable
    with open('shakespeare.txt','r') as f:

      text=f.read()  # Here I am reading the file

      text=text.lower()   # convert all letters to lower case

      text = re.sub(r'[^\w+\s+]', '', text) # Using regular expressions to remove punctuation

      words=text.split()

    ### END CODE HERE ###

    return words

Note, in the following cell, 'words' is converted to a python `set`. This eliminates any duplicate entries.

In [ ]:
# Replace <path to shakespeare.txt> with the actual path to your file
word_l = process_data("/content/shakespeare.txt")
vocab = set(word_l)  # this will be your new vocabulary
print(f"The first ten words in the text are: \n{word_l[0:10]}")
print(f"There are {len(vocab)} unique words in the vocabulary.")

The first ten words in the text are: 
['o', 'for', 'a', 'muse', 'of', 'fire', 'that', 'would', 'ascend', 'the']
There are 6457 unique words in the vocabulary.


#### Expected Output
```Python
The first ten words in the text are:
['o', 'for', 'a', 'muse', 'of', 'fire', 'that', 'would', 'ascend', 'the']
There are 6116 unique words in the vocabulary.
```

In [ ]:
# Unit-tests for process_data
def test_process_data(target):

    failed_cases = []
    successful_cases = 0

    test_cases = [
        {
            "name": "default_check",
            # Replace <path to shakespeare.txt> with the actual path to your file
            "input": {"file_name": "/content/shakespeare.txt"},
            "expected": {
                "expected_output_head": [
                    "o",
                    "for",
                    "a",
                    "muse",
                    "of",
                    "fire",
                    "that",
                    "would",
                    "ascend",
                    "the",
                ],
                "expected_output_tail": [
                    "whilst",
                    "you",
                    "abide",
                    "here",
                    "enobarbus",
                    "humbly",
                    "sir",
                    "i",
                    "thank",
                    "you",
                ],
                "expected_n_words": 6116,
            },
        }
    ]

    for test_case in test_cases:
        result = target(**test_case["input"])

        try:
            assert result[:10] == test_case["expected"]["expected_output_head"]
            successful_cases += 1
        except:
            failed_cases.append(
                {
                    "name": "default_check",
                    "expected": test_case["expected"]["expected_output_head"],
                    "got": result[:10],
                }
            )
            print(
                f"Wrong output. Take a look at how you are reading the file.\n\tExpected: {failed_cases[-1].get('expected')}.\n\tGot: {failed_cases[-1].get('got')}."
            )

        try:
            assert result[-10:] == test_case["expected"]["expected_output_tail"]
            successful_cases += 1
        except:
            failed_cases.append(
                {
                    "name": "default_check",
                    "expected": test_case["expected"]["expected_output_tail"],
                    "got": result[:10],
                }
            )
            print(
                f"Wrong output. Take a look at how you are reading the file.\n\tExpected: {failed_cases[-1].get('expected')}.\n\tGot: {failed_cases[-1].get('got')}."
            )

        n_words = len(set(result))
        try:
            assert n_words == test_case["expected"]["expected_n_words"]
            successful_cases += 1
        except:
            failed_cases.append(
                {
                    "name": "default_check",
                    "expected": test_case["expected"]["expected_n_words"],
                    "got": n_words,
                }
            )
            print(
                f"Wrong number of words. Take a look at how you are extracting every word in the list.\n\tExpected: {failed_cases[-1].get('expected')}.\n\tGot: {failed_cases[-1].get('got')}."
            )

    if len(failed_cases) == 0:
        print("\033[92m All tests passed")
    else:
        print("\033[92m", successful_cases, " Tests passed")
        print("\033[91m", len(failed_cases), " Tests failed")

In [ ]:
# Test your function
test_process_data(process_data)

Wrong number of words. Take a look at how you are extracting every word in the list.
	Expected: 6116.
	Got: 6457.
 2  Tests passed
 1  Tests failed


<a name='ex-2'></a>
### Exercise 2 - get_count

Implement a `get_count` function that returns a dictionary
- The dictionary's keys are words
- The value for each word is the number of times that word appears in the corpus.

For example, given the following sentence: **"I am happy because I am learning"**, your dictionary should return the following:
<table style="width:20%">

  <tr>
    <td> <b>Key </b>  </td>
    <td> <b>Value </b> </td>


  </tr>
  <tr>
    <td> I  </td>
    <td> 2</td>

  </tr>
   
  <tr>
    <td>am</td>
    <td>2</td>
  </tr>

  <tr>
    <td>happy</td>
    <td>1</td>
  </tr>
  
   <tr>
    <td>because</td>
    <td>1</td>
  </tr>
  
   <tr>
    <td>learning</td>
    <td>1</td>
  </tr>
</table>


**Instructions**:
Implement a `get_count` which returns a dictionary where the key is a word and the value is the number of times the word appears in the list.  


<details>    
<summary>
    <font size="3" color="darkgreen"><b>Hints</b></font>
</summary>
<p>
<ul>
    <li>Try implementing this using a for loop and a regular dictionary. This may be good practice for similar coding interview questions</li>
    <li>You can also use defaultdict instead of a regular dictionary, along with the for loop</li>
    <li>Otherwise, to skip using a `for` loop, you can use Python's <a href="https://docs.python.org/3.7/library/collections.html#collections.Counter" > Counter class</a> </li>
</ul>
</p>

In [ ]:
def get_count(word_l):
    """
    Input:
        word_l: a list of words representing the corpus.

    Output:
        word_count_dict: The wordcount dictionary where key is the word and value is its frequency.
    """

    word_count_dict = {}  # fill this with word counts
    ### START CODE HERE
    # Iterate over each word in the list
    for word in word_l:
        # If the word is already in the dictionary, increment its count
        if word in word_count_dict:
            word_count_dict[word] += 1
        # If the word is not in the dictionary, add it with a count of 1
        else:
            word_count_dict[word] = 1

    ### END CODE HERE ###
    return word_count_dict

In [ ]:
word_count_dict = get_count(word_l)
print(f"There are {len(word_count_dict)} key values pairs")
print(f"The count for the word 'thee' is {word_count_dict.get('thee',0)}")

There are 6457 key values pairs
The count for the word 'thee' is 240



#### Expected Output
```Python
There are 6116 key values pairs
The count for the word 'thee' is 240
```

In [ ]:
# Unit-tests for get_count
def test_get_count(target, word_l):
    failed_cases = []
    successful_cases = 0

    test_cases = [
        {
            "name": "default_check",
            "input": {"word_l": word_l},
            "expected": {
                "expected_key_value_pairs": 6116,
                "expected_count_thee": 240,
                "expected_count_esteemed": 3,
                "expected_count_your": 397,
            },
        },
        {
            "name": "small_head_set_check",
            "input": {"word_l": word_l[:1000]},
            "expected": {
                "expected_key_value_pairs": 487,
                "expected_count_thee": 0,
                "expected_count_esteemed": -1,
                "expected_count_your": 4,
            },
        },
        {
            "name": "medium_tail_set_check",
            "input": {"word_l": word_l[-10000:]},
            "expected": {
                "expected_key_value_pairs": 2080,
                "expected_count_thee": 18,
                "expected_count_esteemed": 1,
                "expected_count_your": 57,
            },
        },
    ]

    for test_case in test_cases:
        result = target(**test_case["input"])

        try:
            assert isinstance(result, collections.Counter) or isinstance(result, dict)
            successful_cases += 1
        except:
            failed_cases.append(
                {
                    "name": test_case["name"],
                    "expected": "dict or collections.Counter",
                    "got": str(type(result)),
                }
            )
            print(
                f"Wrong output type.\n\tExpected: {failed_cases[-1].get('expected')}.\n\tGot: {failed_cases[-1].get('got')}."
            )

        try:
            assert len(result) == test_case["expected"]["expected_key_value_pairs"]
            successful_cases += 1
        except:
            failed_cases.append(
                {
                    "name": test_case["name"],
                    "expected": test_case["expected"]["expected_n_words"],
                    "got": n_words,
                }
            )
            print(
                f"Wrong number of key-value pairs. Check that you are not skipping any word in the loop.\n\tExpected: {failed_cases[-1].get('expected')}.\n\tGot: {failed_cases[-1].get('got')}."
            )

        try:
            assert result.get("thee", 0) == test_case["expected"]["expected_count_thee"]
            successful_cases += 1
        except:
            failed_cases.append(
                {
                    "name": test_case["name"],
                    "expected": test_case["expected"]["expected_count_thee"],
                    "got": result.get("thee", 0),
                }
            )
            print(
                f"Wrong word count for word 'thee'. Check your loop implementation.\n\tExpected: {failed_cases[-1].get('expected')}.\n\tGot: {failed_cases[-1].get('got')}."
            )

        try:
            assert (
                result.get("esteemed", -1)
                == test_case["expected"]["expected_count_esteemed"]
            )
            successful_cases += 1
        except:
            failed_cases.append(
                {
                    "name": test_case["name"],
                    "expected": test_case["expected"]["expected_count_esteemed"],
                    "got": result.get("esteemed", -1),
                }
            )
            print(
                f"Wrong word count for word 'esteemed'. Check your loop implementation.\n\tExpected: {failed_cases[-1].get('expected')}.\n\tGot: {failed_cases[-1].get('got')}."
            )

        try:
            assert result.get("your", 0) == test_case["expected"]["expected_count_your"]
            successful_cases += 1
        except:
            failed_cases.append(
                {
                    "name": test_case["name"],
                    "expected": test_case["expected"]["expected_count_your"],
                    "got": result.get("your", 0),
                }
            )
            print(
                f"Wrong word count for word 'esteemed'. Check your loop implementation.\n\tExpected: {failed_cases[-1].get('expected')}.\n\tGot: {failed_cases[-1].get('got')}."
            )

    if len(failed_cases) == 0:
        print("\033[92m All tests passed")
    else:
        print("\033[92m", successful_cases, " Tests passed")
        print("\033[91m", len(failed_cases), " Tests failed")

In [ ]:
# Test your function
test_get_count(get_count, word_l)

KeyError: 'expected_n_words'

<a name='ex-3'></a>
### Exercise 3 - get_probs
Given the dictionary of word counts, compute the probability that each word will appear if randomly selected from the corpus of words.

$$P(w_i) = \frac{C(w_i)}{M} \tag{Eqn-2}$$
where

$C(w_i)$ is the total number of times $w_i$ appears in the corpus.

$M$ is the total number of words in the corpus.

For example, the probability of the word 'am' in the sentence **'I am happy because I am learning'** is:

$$P(am) = \frac{C(w_i)}{M} = \frac {2}{7} \tag{Eqn-3}.$$

**Instructions:** Implement `get_probs` function which gives you the probability
that a word occurs in a sample. This returns a dictionary where the keys are words, and the value for each word is its probability in the corpus of words.

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Hints</b></font>
</summary>
<p>
General advice
<ul>
    <li> Use dictionary.values() </li>
    <li> Use sum() </li>
    <li> The cardinality (number of words in the corpus should be equal to len(word_l).  You will calculate this same number, but using the word count dictionary.</li>
</ul>
    
If you're using a for loop:
<ul>
    <li> Use dictionary.keys() </li>
</ul>
    
If you're using a dictionary comprehension:
<ul>
    <li>Use dictionary.items() </li>
</ul>
</p>


In [ ]:
def get_probs(word_count_dict):
    """
    Input:
        word_count_dict: The wordcount dictionary where key is the word and value is its frequency.

    Output:
        probs: A dictionary where keys are the words and the values are the probability that a word will occur.
    """
    probs = {}  # return this variable correctly


    ### START CODE HERE ###

    # get the total count of words for all words in the dictionary

     # Get the total count of words in the corpus
    total_count = sum(word_count_dict.values())

    # For each word in the word_count_dict, calculate its probability
    for word, count in word_count_dict.items():
        probs[word] = count / total_count        # --> # P(wi) = C(wi) / M

    ### END CODE HERE ###
    return probs

In [ ]:
probs = get_probs(word_count_dict)
print(f"Length of probs is {len(probs)}")
print(f"P('thee') is {probs['thee']:.4f}")

Length of probs is 6457
P('thee') is 0.0046


#### Expected Output

```Python
Length of probs is 6116
P('thee') is 0.0045
```

In [ ]:
# Unit-tests for get_probs
def test_get_probs(target, word_count_dict):
    failed_cases = []
    successful_cases = 0

    test_cases = [
        {
            "name": "default_check",
            "input": {"word_count_dict": word_count_dict},
            "expected": {
                "expected_prob_length": 6116,
                "expected_prob_thee": 0.0045,
                "expected_prob_esteemed": 0.0001,
                "expected_prob_your": 0.0074,
            },
        },
        {
            "name": "small_check",
            "input": {
                "word_count_dict": {
                    key: word_count_dict[key]
                    for key in [
                        "for",
                        "a",
                        "fire",
                        "ascend",
                        "esteemed",
                        "your",
                        "thee",
                    ]
                }
            },
            "expected": {
                "expected_prob_length": 7,
                "expected_prob_thee": 0.1267,
                "expected_prob_esteemed": 0.0016,
                "expected_prob_your": 0.2096,
            },
        },
    ]

    for test_case in test_cases:
        result = target(**test_case["input"])

        try:
            assert isinstance(result, dict)
            successful_cases += 1
        except:
            failed_cases.append(
                {"name": test_case["name"], "expected": dict, "got": type(result),}
            )
            print(
                f"Wrong output type.\n\tExpected: {failed_cases[-1].get('expected')}.\n\tGot: {failed_cases[-1].get('got')}."
            )

        try:
            assert len(result) == test_case["expected"]["expected_prob_length"]
            successful_cases += 1
        except:
            failed_cases.append(
                {
                    "name": test_case["name"],
                    "expected": test_case["expected"]["expected_prob_length"],
                    "got": len(result),
                }
            )
            print(
                f"Wrong number of probabilities in the dictionary.\n\tExpected: {failed_cases[-1].get('expected')}.\n\tGot: {failed_cases[-1].get('got')}."
            )

        try:
            assert np.isclose(
                round(result["thee"], 4), test_case["expected"]["expected_prob_thee"],
            )
            successful_cases += 1
        except:
            failed_cases.append(
                {
                    "name": test_case["name"],
                    "expected": test_case["expected"]["expected_prob_thee"],
                    "got": result["thee"],
                }
            )
            print(
                f"Wrong probability for word 'thee'.\n\tExpected: {failed_cases[-1].get('expected')}.\n\tGot: {failed_cases[-1].get('got')}."
            )

        try:
            assert np.isclose(
                round(result["esteemed"], 4),
                test_case["expected"]["expected_prob_esteemed"],
            )
            successful_cases += 1
        except:
            failed_cases.append(
                {
                    "name": test_case["name"],
                    "expected": test_case["expected"]["expected_prob_esteemed"],
                    "got": result["esteemed"],
                }
            )
            print(
                f"Wrong probability for word 'esteemed'.\n\tExpected: {failed_cases[-1].get('expected')}.\n\tGot: {failed_cases[-1].get('got')}."
            )

        try:
            assert np.isclose(
                round(result["your"], 4), test_case["expected"]["expected_prob_your"],
            )
            successful_cases += 1
        except:
            failed_cases.append(
                {
                    "name": test_case["name"],
                    "expected": test_case["expected"]["expected_prob_your"],
                    "got": result["your"],
                }
            )
            print(
                f"Wrong probability for word 'your'.\n\tExpected: {failed_cases[-1].get('expected')}.\n\tGot: {failed_cases[-1].get('got')}."
            )

    if len(failed_cases) == 0:
        print("\033[92m All tests passed")
    else:
        print("\033[92m", successful_cases, " Tests passed")
        print("\033[91m", len(failed_cases), " Tests failed")

In [ ]:
# Test your function
test_get_probs(get_probs, word_count_dict)

Wrong number of probabilities in the dictionary.
	Expected: 6116.
	Got: 6457.
Wrong probability for word 'thee'.
	Expected: 0.0045.
	Got: 0.004601138781848507.
Wrong probability for word 'your'.
	Expected: 0.0074.
	Got: 0.007611050401641073.
Wrong probability for word 'thee'.
	Expected: 0.1267.
	Got: 0.12745618693574085.
Wrong probability for word 'your'.
	Expected: 0.2096.
	Got: 0.21083377588953797.
 5  Tests passed
 5  Tests failed


<a name='2'></a>
## 2 - String Manipulations

Now that you have computed $P(w_i)$ for all the words in the corpus, you will write a few functions to manipulate strings so that you can edit the erroneous strings and return the right spellings of the words. In this section, you will implement four functions:

* `delete_letter`: given a word, it returns all the possible strings that have **one character removed**.
* `switch_letter`: given a word, it returns all the possible strings that have **two adjacent letters switched**.
* `replace_letter`: given a word, it returns all the possible strings that have **one character replaced by another different letter**.
* `insert_letter`: given a word, it returns all the possible strings that have an **additional character inserted**.


#### List comprehensions

String and list manipulation in python will often make use of a python feature called  [list comprehensions](https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions). The routines below must be implemented using list comprehensions

Python List Comprehensions embed a looping structure inside of a list declaration, collapsing many lines of code into a single line. If you are not familiar with them, they seem slightly out of order relative to for loops.

<div style="width:image width px; font-size:100%; text-align:center;"><img src='https://drive.google.com/uc?export&id=1B5hS57uAyOdZzvovwTZVmOMcXswxx8m6' alt="alternate text" width="width" height="height"  style="width:800px;height:400px;"/> Figure 2 </div>

The diagram above shows that the components of a list comprehension are the same components you would find in a typical for loop that appends to a list, but in a different order. With that in mind, we'll continue the specifics of this assignment. We will be very descriptive for the first function, `deletes()`, and less so in later functions as you become familiar with list comprehensions.

<a name='ex-4'></a>
### Exercise 4 - delete_letter

**Instructions for delete_letter():** Implement a `delete_letter()` function that, given a word, returns a list of strings with one character deleted.

For example, given the word **nice**, it would return the set: {'ice', 'nce', 'nic', 'nie'}.

**Step 1:** Create a list of 'splits'. This is all the ways you can split a word into Left and Right: For example,   
'nice is split into : `[('', 'nice'), ('n', 'ice'), ('ni', 'ce'), ('nic', 'e'), ('nice', '')]`
This is common to all four functions (delete, replace, switch, insert).


<div style="width:image width px; font-size:100%; text-align:center;"><img src='https://drive.google.com/uc?export&id=1zDX3cACgMI1tzC--HpzQk0eH60m_-FsL' alt="alternate text" width="width" height="height" style="width:650px;height:200px;" /> Figure 3 </div>

**Step 2:** This is specific to `delete_letter`. Here, we are generating all words that result from deleting one character.  
This can be done in a single line with a list comprehension. You can make use of this type of syntax:  
`[f(a,b) for a, b in splits if condition]`  

For our 'nice' example you get:
['ice', 'nce', 'nie', 'nic']

<div style="width:image width px; font-size:100%; text-align:center;"><img src='https://drive.google.com/uc?export&id=156tgsFHb5ya2AkeDPnAo_jmV-hwQaeXQ' alt="alternate text" width="width" height="height" style="width:550px;height:300px;" /> Figure 4 </div>

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Level 2 Hints</b></font>
</summary>
<p>
<ul>
    <li><a href="" > Use array slicing like my_string[0:2] </a> </li>
    <li><a href="" > Use list comprehensions or for loops </a> </li>
</ul>
</p>


<details>    
<summary>
    <font size="3" color="darkgreen"><b>Level 3 Hints</b></font>
</summary>
<p>
<ul>
    <li>splits: Use array slicing, like my_str[0:2], to separate a string into two pieces.</li>
    <li>Do this in a loop or list comprehension, so that you have a list of tuples.
    <li> For example, "cake" can get split into "ca" and "ke". They're stored in a tuple ("ca","ke"), and the tuple is appended to a list.  We'll refer to these as L and R, so the tuple is (L,R)</li>
    <li>When choosing the range for your loop, if you input the word "cans" and generate the tuple  ('cans',''), make sure to include an if statement to check the length of that right-side string (R) in the tuple (L,R) </li>
    <li>deletes: Go through the list of tuples and combine the two strings together. You can use the + operator to combine two strings</li>
    <li>When combining the tuples, make sure that you leave out a middle character.</li>
    <li>Use array slicing to leave out the first character of the right substring.</li>
</ul>
</p>

In [ ]:
def delete_letter(word, verbose=False):
    """
    Input:
        word: the string/word for which you will generate all possible words
                in the vocabulary which have 1 missing character
    Output:
        delete_l: a list of all possible strings obtained by deleting 1 character from word
    """

    delete_l = []
    split_l = []

    ### START CODE HERE ###

    # Generate all possible strings by removing one character from the word
    for i in range(len(word)):

        # Create a new string by excluding the character at index i
        new_word = word[:i] + word[i+1:]
        delete_l.append(new_word)
        split_l.append((word[:i], word[i+1:]))  # For debugging, record the split parts

    # if verbose:
    #     print(f"Input word: {word}")
    #     print(f"Split list: {split_l}")
    #     print(f"Delete list: {delete_l}")

    if verbose: print(f"input word {word}, \nsplit_l = {split_l}, \ndelete_l = {delete_l}")

   ### END CODE HERE ###
    return  delete_l

In [ ]:
delete_word_l = delete_letter(word="cans",
                        verbose=True)

input word cans, 
split_l = [('', 'ans'), ('c', 'ns'), ('ca', 's'), ('can', '')], 
delete_l = ['ans', 'cns', 'cas', 'can']


#### Expected Output
```CPP
Note: You might get a slightly different result with split_l

input word cans,
split_l = [('', 'cans'), ('c', 'ans'), ('ca', 'ns'), ('can', 's')],
delete_l = ['ans', 'cns', 'cas', 'can']
```

#### Note 1
- Notice how it has the extra tuple `('cans', '')`.
- This will be fine as long as you have checked the size of the right-side substring in tuple (L,R).
- Can you explain why this will give you the same result for the list of deletion strings (delete_l)?

```CPP
input word cans,
split_l = [('', 'cans'), ('c', 'ans'), ('ca', 'ns'), ('can', 's'), ('cans', '')],
delete_l = ['ans', 'cns', 'cas', 'can']
```

#### Note 2
If you end up getting the same word as your input word, like this:

```Python
input word cans,
split_l = [('', 'cans'), ('c', 'ans'), ('ca', 'ns'), ('can', 's'), ('cans', '')],
delete_l = ['ans', 'cns', 'cas', 'can', 'cans']
```

- Check how you set the `range`.
- See if you check the length of the string on the right-side of the split.

In [ ]:
# test # 2
print(f"Number of outputs of delete_letter('at') is {len(delete_letter('at'))}")

Number of outputs of delete_letter('at') is 2


#### Expected output

```CPP
Number of outputs of delete_letter('at') is 2
```

In [ ]:
# Unit-tests for delete_letter
def test_delete_letter(target):
    failed_cases = []
    successful_cases = 0

    test_cases = [
        {
            "name": "default_check",
            "input": {"word": "cans"},
            "expected": ["ans", "cns", "cas", "can"],
        },
        {
            "name": "small_default_check",
            "input": {"word": "at"},
            "expected": ["t", "a"],
        },
        {
            "name": "long_check",
            "input": {"word": "esteemed"},
            "expected": [
                "steemed",
                "eteemed",
                "eseemed",
                "estemed",
                "estemed",
                "esteeed",
                "esteemd",
                "esteeme",
            ],
        },
    ]

    for test_case in test_cases:
        result = target(**test_case["input"])

        try:
            assert isinstance(result, list)
            successful_cases += 1
        except:
            failed_cases.append(
                {"name": test_case["name"], "expected": list, "got": type(result)}
            )
            print(
                f"Wrong output type.\n\tExpected: {failed_cases[-1].get('expected')}.\n\tGot: {failed_cases[-1].get('got')}."
            )

        try:
            assert sorted(result) == sorted(test_case["expected"])
            successful_cases += 1
        except:
            failed_cases.append(
                {
                    "name": test_case["name"],
                    "expected": test_case["expected"],
                    "got": result,
                }
            )
            print(
                f"Wrong output values.\n\tExpected: {failed_cases[-1].get('expected')}.\n\tGot: {failed_cases[-1].get('got')}."
            )

    if len(failed_cases) == 0:
        print("\033[92m All tests passed")
    else:
        print("\033[92m", successful_cases, " Tests passed")
        print("\033[91m", len(failed_cases), " Tests failed")

In [ ]:
# Test your function
test_delete_letter(delete_letter)

 All tests passed


<a name='ex-5'></a>
### Exercise 5 - switch_letter

**Instructions for switch_letter()**: Now implement a function that switches two letters in a word. It takes in a word and returns a list of all the possible switches of two letters **that are adjacent to each other**.
- For example, given the word 'eta', it returns {'eat', 'tea'}, but does not return 'ate'.

**Step 1:** is the same as in delete_letter()  
**Step 2:** A list comprehension or for loop which forms strings by swapping adjacent letters. This is of the form:  
`[f(L,R) for L, R in splits if condition]`  where 'condition' will test the length of R in a given iteration. See below.

<div style="width:image width px; font-size:100%; text-align:center;"><img src='https://drive.google.com/uc?export&id=1WF3ksAGtfA25q_WM2scY8FXQDdby26ZY' alt="alternate text" width="width" height="height" style="width:600px;height:200px;"/> Figure 5 </div>      

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Level 2 Hints</b></font>
</summary>
<p>
<ul>
    <li><a href="" > Use array slicing like my_string[0:2] </a> </li>
    <li><a href="" > Use list comprehensions or for loops </a> </li>
    <li>To do a switch, think of the whole word as divided into 4 distinct parts.  Write out 'cupcakes' on a piece of paper and see how you can split it into ('cupc', 'k', 'a', 'es')</li>
</ul>
</p>


<details>    
<summary>
    <font size="3" color="darkgreen"><b>Level 3 Hints</b></font>
</summary>
<p>
<ul>
    <li>splits: Use array slicing, like my_str[0:2], to separate a string into two pieces.</li>
    <li>Splitting is the same as for delete_letter</li>
    <li>To perform the switch, go through the list of tuples and combine four strings together. You can use the + operator to combine strings</li>
    <li>The four strings will be the left substring from the split tuple, followed by the first (index 1) character of the right substring, then the zero-th character (index 0) of the right substring, and then the remaining part of the right substring.</li>
    <li>Unlike delete_letter, you will want to check that your right substring is at least a minimum length.  To see why, review the previous hint bullet point (directly before this one).</li>
</ul>
</p>

In [ ]:
def switch_letter(word, verbose=False):
    """
    Input:
        word: input string

    Output:
        switches: a list of all possible strings with one adjacent charater switched
    """

    switch_l = []
    split_l = []

    ### START CODE HERE ###

     # Generate all possible strings by switching adjacent letters
    for i in range(len(word) - 1):
        # Swap characters at index i and i+1
        new_word = word[:i] + word[i+1] + word[i] + word[i+2:]
        switch_l.append(new_word)
        split_l.append((word[:i], word[i], word[i+1], word[i+2:]))  # For debugging, record the split parts

    ### END CODE HERE ###

    if verbose: print(f"Input word = {word} \nsplit_l = {split_l} \nswitch_l = {switch_l}")

    return switch_l

In [ ]:
switch_word_l = switch_letter(word="eta",
                         verbose=True)

Input word = eta 
split_l = [('', 'e', 't', 'a'), ('e', 't', 'a', '')] 
switch_l = ['tea', 'eat']


#### Expected output

```Python
Input word = eta
split_l = [('', 'eta'), ('e', 'ta'), ('et', 'a')]
switch_l = ['tea', 'eat']
```

#### Note 1

You may get this:
```Python
Input word = eta
split_l = [('', 'eta'), ('e', 'ta'), ('et', 'a'), ('eta', '')]
switch_l = ['tea', 'eat']
```
- Notice how it has the extra tuple `('eta', '')`.
- This is also correct.
- Can you think of why this is the case?

#### Note 2

If you get an error
```Python
IndexError: string index out of range
```
- Please see if you have checked the length of the strings when switching characters.

In [ ]:
# test # 2
print(f"Number of outputs of switch_letter('at') is {len(switch_letter('at'))}")

Number of outputs of switch_letter('at') is 1


#### Expected output

```CPP
Number of outputs of switch_letter('at') is 1
```

In [ ]:
# Unit-tests for switch_letter
def test_switch_letter(target):
    failed_cases = []
    successful_cases = 0

    test_cases = [
        {
            "name": "default_check",
            "input": {"word": "eta"},
            "expected": ["tea", "eat"],
        },
        {"name": "small_default_check", "input": {"word": "at"}, "expected": ["ta"],},
        {
            "name": "long_check",
            "input": {"word": "satr"},
            "expected": ["astr", "star", "sart"],
        },
    ]

    for test_case in test_cases:
        result = target(**test_case["input"])

        try:
            assert isinstance(result, list)
            successful_cases += 1
        except:
            failed_cases.append(
                {"name": test_case["name"], "expected": list, "got": type(result)}
            )
            print(
                f"Wrong output type.\n\tExpected: {failed_cases[-1].get('expected')}.\n\tGot: {failed_cases[-1].get('got')}."
            )

        try:
            assert sorted(result) == sorted(test_case["expected"])
            successful_cases += 1
        except:
            failed_cases.append(
                {
                    "name": test_case["name"],
                    "expected": test_case["expected"],
                    "got": result,
                }
            )
            print(
                f"Wrong output values.\n\tExpected: {failed_cases[-1].get('expected')}.\n\tGot: {failed_cases[-1].get('got')}."
            )

    if len(failed_cases) == 0:
        print("\033[92m All tests passed")
    else:
        print("\033[92m", successful_cases, " Tests passed")
        print("\033[91m", len(failed_cases), " Tests failed")

In [ ]:
# Test your function
test_switch_letter(switch_letter)

 All tests passed


<a name='ex-6'></a>
### Exercise 6 - replace_letter
**Instructions for replace_letter()**: Now implement a function that takes in a word and returns a list of strings with one **replaced letter** from the original word.

**Step 1:** is the same as in `delete_letter()`

**Step 2:** A list comprehension or for loop which form strings by replacing letters.  This can be of the form:  
`[f(a,b,c) for a, b in splits if condition for c in string]`   Note the use of the second for loop.  
It is expected in this routine that one or more of the replacements will include the original word. For example, replacing the first letter of 'ear' with 'e' will return 'ear'.

**Step 3:** Remove the original input letter from the output.

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Hints</b></font>
</summary>
<p>
<ul>
    <li>To remove a word from a list, you may use the method .replace of a list. Note that the .remove method removes the first occurrence of an element, so you need to assure that every occurrence is removed. A while loop to check if the element is in the list may help.</li>
    <li>Another way is using list comprehension so you directly remove the word in the conditions.</li>
</ul>
</p>

In [ ]:
def replace_letter(word, verbose=False):
    """
    Input:
        word: the input string/word

    Output:
        replaces: a list of all possible strings where we replaced one letter from the original word.
    """

    letters = 'abcdefghijklmnopqrstuvwxyz'

    replace_l = []
    split_l = []

    ### START CODE HERE ###

    # Generate all possible strings by replacing one letter
    for i in range(len(word)):
        for letter in letters:
            if letter != word[i]:  # Only replace with a different letter
                new_word = word[:i] + letter + word[i+1:]
                replace_l.append(new_word)
                split_l.append((word[:i], letter, word[i+1:]))  # For debugging, record the split parts

    # Remove the original word from the results if it appears
    replace_l = [word for word in replace_l if word != word]

    ### END CODE HERE ###

    # Sort the list, for easier viewing
    replace_l = sorted(replace_l)

    if verbose: print(f"Input word = {word} \nsplit_l = {split_l} \nreplace_l {replace_l}")

    return replace_l

In [ ]:
replace_l = replace_letter(word='can',
                              verbose=True)

Input word = can 
split_l = [('', 'a', 'an'), ('', 'b', 'an'), ('', 'd', 'an'), ('', 'e', 'an'), ('', 'f', 'an'), ('', 'g', 'an'), ('', 'h', 'an'), ('', 'i', 'an'), ('', 'j', 'an'), ('', 'k', 'an'), ('', 'l', 'an'), ('', 'm', 'an'), ('', 'n', 'an'), ('', 'o', 'an'), ('', 'p', 'an'), ('', 'q', 'an'), ('', 'r', 'an'), ('', 's', 'an'), ('', 't', 'an'), ('', 'u', 'an'), ('', 'v', 'an'), ('', 'w', 'an'), ('', 'x', 'an'), ('', 'y', 'an'), ('', 'z', 'an'), ('c', 'b', 'n'), ('c', 'c', 'n'), ('c', 'd', 'n'), ('c', 'e', 'n'), ('c', 'f', 'n'), ('c', 'g', 'n'), ('c', 'h', 'n'), ('c', 'i', 'n'), ('c', 'j', 'n'), ('c', 'k', 'n'), ('c', 'l', 'n'), ('c', 'm', 'n'), ('c', 'n', 'n'), ('c', 'o', 'n'), ('c', 'p', 'n'), ('c', 'q', 'n'), ('c', 'r', 'n'), ('c', 's', 'n'), ('c', 't', 'n'), ('c', 'u', 'n'), ('c', 'v', 'n'), ('c', 'w', 'n'), ('c', 'x', 'n'), ('c', 'y', 'n'), ('c', 'z', 'n'), ('ca', 'a', ''), ('ca', 'b', ''), ('ca', 'c', ''), ('ca', 'd', ''), ('ca', 'e', ''), ('ca', 'f', ''), ('ca', 'g', ''), ('

#### Expected Output**:
```Python
Input word = can
split_l = [('', 'can'), ('c', 'an'), ('ca', 'n')]
replace_l ['aan', 'ban', 'caa', 'cab', 'cac', 'cad', 'cae', 'caf', 'cag', 'cah', 'cai', 'caj', 'cak', 'cal', 'cam', 'cao', 'cap', 'caq', 'car', 'cas', 'cat', 'cau', 'cav', 'caw', 'cax', 'cay', 'caz', 'cbn', 'ccn', 'cdn', 'cen', 'cfn', 'cgn', 'chn', 'cin', 'cjn', 'ckn', 'cln', 'cmn', 'cnn', 'con', 'cpn', 'cqn', 'crn', 'csn', 'ctn', 'cun', 'cvn', 'cwn', 'cxn', 'cyn', 'czn', 'dan', 'ean', 'fan', 'gan', 'han', 'ian', 'jan', 'kan', 'lan', 'man', 'nan', 'oan', 'pan', 'qan', 'ran', 'san', 'tan', 'uan', 'van', 'wan', 'xan', 'yan', 'zan']
```
- Note how the input word 'can' should not be one of the output words.

#### Note 1
If you get something like this:

```Python
Input word = can
split_l = [('', 'can'), ('c', 'an'), ('ca', 'n'), ('can', '')]
replace_l ['aan', 'ban', 'caa', 'cab', 'cac', 'cad', 'cae', 'caf', 'cag', 'cah', 'cai', 'caj', 'cak', 'cal', 'cam', 'cao', 'cap', 'caq', 'car', 'cas', 'cat', 'cau', 'cav', 'caw', 'cax', 'cay', 'caz', 'cbn', 'ccn', 'cdn', 'cen', 'cfn', 'cgn', 'chn', 'cin', 'cjn', 'ckn', 'cln', 'cmn', 'cnn', 'con', 'cpn', 'cqn', 'crn', 'csn', 'ctn', 'cun', 'cvn', 'cwn', 'cxn', 'cyn', 'czn', 'dan', 'ean', 'fan', 'gan', 'han', 'ian', 'jan', 'kan', 'lan', 'man', 'nan', 'oan', 'pan', 'qan', 'ran', 'san', 'tan', 'uan', 'van', 'wan', 'xan', 'yan', 'zan']
```
- Notice how split_l has an extra tuple `('can', '')`, but the output is still the same, so this is okay.

#### Note 2
If you get something like this:
```Python
Input word = can
split_l = [('', 'can'), ('c', 'an'), ('ca', 'n'), ('can', '')]
replace_l ['aan', 'ban', 'caa', 'cab', 'cac', 'cad', 'cae', 'caf', 'cag', 'cah', 'cai', 'caj', 'cak', 'cal', 'cam', 'cana', 'canb', 'canc', 'cand', 'cane', 'canf', 'cang', 'canh', 'cani', 'canj', 'cank', 'canl', 'canm', 'cann', 'cano', 'canp', 'canq', 'canr', 'cans', 'cant', 'canu', 'canv', 'canw', 'canx', 'cany', 'canz', 'cao', 'cap', 'caq', 'car', 'cas', 'cat', 'cau', 'cav', 'caw', 'cax', 'cay', 'caz', 'cbn', 'ccn', 'cdn', 'cen', 'cfn', 'cgn', 'chn', 'cin', 'cjn', 'ckn', 'cln', 'cmn', 'cnn', 'con', 'cpn', 'cqn', 'crn', 'csn', 'ctn', 'cun', 'cvn', 'cwn', 'cxn', 'cyn', 'czn', 'dan', 'ean', 'fan', 'gan', 'han', 'ian', 'jan', 'kan', 'lan', 'man', 'nan', 'oan', 'pan', 'qan', 'ran', 'san', 'tan', 'uan', 'van', 'wan', 'xan', 'yan', 'zan']
```
- Notice how there are strings that are 1 letter longer than the original word, such as `cana`.
- Please check for the case when there is an empty string `''`, and if so, do not use that empty string when setting replace_l.

In [ ]:
# test # 2
print(f"Number of outputs of replace_letter('at') is {len(replace_letter('at'))}")

Number of outputs of replace_letter('at') is 0


#### Expected output
```CPP
Number of outputs of replace_letter('at') is 50
```

In [ ]:
# Unit-tests for replace_letter
def test_replace_letter(target):
    failed_cases = []
    successful_cases = 0

    test_cases = [
        {
            "name": "default_check",
            "input": {"word": "can"},
            "expected": [
                "aan",
                "ban",
                "caa",
                "cab",
                "cac",
                "cad",
                "cae",
                "caf",
                "cag",
                "cah",
                "cai",
                "caj",
                "cak",
                "cal",
                "cam",
                "cao",
                "cap",
                "caq",
                "car",
                "cas",
                "cat",
                "cau",
                "cav",
                "caw",
                "cax",
                "cay",
                "caz",
                "cbn",
                "ccn",
                "cdn",
                "cen",
                "cfn",
                "cgn",
                "chn",
                "cin",
                "cjn",
                "ckn",
                "cln",
                "cmn",
                "cnn",
                "con",
                "cpn",
                "cqn",
                "crn",
                "csn",
                "ctn",
                "cun",
                "cvn",
                "cwn",
                "cxn",
                "cyn",
                "czn",
                "dan",
                "ean",
                "fan",
                "gan",
                "han",
                "ian",
                "jan",
                "kan",
                "lan",
                "man",
                "nan",
                "oan",
                "pan",
                "qan",
                "ran",
                "san",
                "tan",
                "uan",
                "van",
                "wan",
                "xan",
                "yan",
                "zan",
            ],
        },
        {
            "name": "small_default_check",
            "input": {"word": "at"},
            "expected": [
                "aa",
                "ab",
                "ac",
                "ad",
                "ae",
                "af",
                "ag",
                "ah",
                "ai",
                "aj",
                "ak",
                "al",
                "am",
                "an",
                "ao",
                "ap",
                "aq",
                "ar",
                "as",
                "au",
                "av",
                "aw",
                "ax",
                "ay",
                "az",
                "bt",
                "ct",
                "dt",
                "et",
                "ft",
                "gt",
                "ht",
                "it",
                "jt",
                "kt",
                "lt",
                "mt",
                "nt",
                "ot",
                "pt",
                "qt",
                "rt",
                "st",
                "tt",
                "ut",
                "vt",
                "wt",
                "xt",
                "yt",
                "zt",
            ],
        },
        {
            "name": "long_check",
            "input": {"word": "star"},
            "expected": [
                "atar",
                "btar",
                "ctar",
                "dtar",
                "etar",
                "ftar",
                "gtar",
                "htar",
                "itar",
                "jtar",
                "ktar",
                "ltar",
                "mtar",
                "ntar",
                "otar",
                "ptar",
                "qtar",
                "rtar",
                "saar",
                "sbar",
                "scar",
                "sdar",
                "sear",
                "sfar",
                "sgar",
                "shar",
                "siar",
                "sjar",
                "skar",
                "slar",
                "smar",
                "snar",
                "soar",
                "spar",
                "sqar",
                "srar",
                "ssar",
                "staa",
                "stab",
                "stac",
                "stad",
                "stae",
                "staf",
                "stag",
                "stah",
                "stai",
                "staj",
                "stak",
                "stal",
                "stam",
                "stan",
                "stao",
                "stap",
                "staq",
                "stas",
                "stat",
                "stau",
                "stav",
                "staw",
                "stax",
                "stay",
                "staz",
                "stbr",
                "stcr",
                "stdr",
                "ster",
                "stfr",
                "stgr",
                "sthr",
                "stir",
                "stjr",
                "stkr",
                "stlr",
                "stmr",
                "stnr",
                "stor",
                "stpr",
                "stqr",
                "strr",
                "stsr",
                "sttr",
                "stur",
                "stvr",
                "stwr",
                "stxr",
                "styr",
                "stzr",
                "suar",
                "svar",
                "swar",
                "sxar",
                "syar",
                "szar",
                "ttar",
                "utar",
                "vtar",
                "wtar",
                "xtar",
                "ytar",
                "ztar",
            ],
        },
    ]

    for test_case in test_cases:
        result = target(**test_case["input"])

        try:
            assert isinstance(result, list)
            successful_cases += 1
        except:
            failed_cases.append(
                {"name": test_case["name"], "expected": list, "got": type(result)}
            )
            print(
                f"Wrong output type.\n\tExpected: {failed_cases[-1].get('expected')}.\n\tGot: {failed_cases[-1].get('got')}."
            )

        try:
            assert len(set(map(len, result))) == 1
            successful_cases += 1
        except:
            failed_cases.append(
                {
                    "name": test_case["name"],
                    "expected": len(test_case["input"]["word"]),
                    "got": set(map(len, result)),
                }
            )
            print(
                f"The list has elements with a different length than the input length.\n\tExpected: {failed_cases[-1].get('expected')}.\n\tGot: {failed_cases[-1].get('got')}."
            )

        try:
            assert sorted(result) == sorted(test_case["expected"])
            successful_cases += 1
        except:
            failed_cases.append(
                {
                    "name": test_case["name"],
                    "expected": test_case["expected"],
                    "got": result,
                }
            )
            print(
                f"Wrong output values.\n\tExpected: {failed_cases[-1].get('expected')}.\n\tGot: {failed_cases[-1].get('got')}."
            )

    if len(failed_cases) == 0:
        print("\033[92m All tests passed")
    else:
        print("\033[92m", successful_cases, " Tests passed")
        print("\033[91m", len(failed_cases), " Tests failed")

In [ ]:
# Test your function
test_replace_letter(replace_letter)

The list has elements with a different length than the input length.
	Expected: 3.
	Got: set().
Wrong output values.
	Expected: ['aan', 'ban', 'caa', 'cab', 'cac', 'cad', 'cae', 'caf', 'cag', 'cah', 'cai', 'caj', 'cak', 'cal', 'cam', 'cao', 'cap', 'caq', 'car', 'cas', 'cat', 'cau', 'cav', 'caw', 'cax', 'cay', 'caz', 'cbn', 'ccn', 'cdn', 'cen', 'cfn', 'cgn', 'chn', 'cin', 'cjn', 'ckn', 'cln', 'cmn', 'cnn', 'con', 'cpn', 'cqn', 'crn', 'csn', 'ctn', 'cun', 'cvn', 'cwn', 'cxn', 'cyn', 'czn', 'dan', 'ean', 'fan', 'gan', 'han', 'ian', 'jan', 'kan', 'lan', 'man', 'nan', 'oan', 'pan', 'qan', 'ran', 'san', 'tan', 'uan', 'van', 'wan', 'xan', 'yan', 'zan'].
	Got: [].
The list has elements with a different length than the input length.
	Expected: 2.
	Got: set().
Wrong output values.
	Expected: ['aa', 'ab', 'ac', 'ad', 'ae', 'af', 'ag', 'ah', 'ai', 'aj', 'ak', 'al', 'am', 'an', 'ao', 'ap', 'aq', 'ar', 'as', 'au', 'av', 'aw', 'ax', 'ay', 'az', 'bt', 'ct', 'dt', 'et', 'ft', 'gt', 'ht', 'it', 'jt', 'k

<a name='ex-7'></a>
### Exercise 7 - insert_letter

**Instructions for insert_letter()**: Now implement a function that takes in a word and returns a list with a letter inserted at every offset.

**Step 1:** is the same as in `delete_letter()`

**Step 2:** This can be a list comprehension of the form:  
`[f(a,b,c) for a, b in splits if condition for c in string]`   

In [ ]:
def insert_letter(word, verbose=False):
    """
    Input:
        word: the input string/word

    Output:
        inserts: a set of all possible strings with one new letter inserted at every offset
    """
    letters = 'abcdefghijklmnopqrstuvwxyz'
    insert_l = []
    split_l = []

    ### START CODE HERE ###

    # Generate all possible strings by inserting one letter at every offset
    for i in range(len(word) + 1):
        for letter in letters:
            new_word = word[:i] + letter + word[i:]
            insert_l.append(new_word)
            split_l.append((word[:i], letter, word[i:]))
    ### END CODE HERE ###

    if verbose: print(f"Input word {word} \nsplit_l = {split_l} \ninsert_l = {insert_l}")

    return insert_l

In [ ]:
insert_l = insert_letter('at', True)
print(f"Number of strings output by insert_letter('at') is {len(insert_l)}")

Input word at 
split_l = [('', 'a', 'at'), ('', 'b', 'at'), ('', 'c', 'at'), ('', 'd', 'at'), ('', 'e', 'at'), ('', 'f', 'at'), ('', 'g', 'at'), ('', 'h', 'at'), ('', 'i', 'at'), ('', 'j', 'at'), ('', 'k', 'at'), ('', 'l', 'at'), ('', 'm', 'at'), ('', 'n', 'at'), ('', 'o', 'at'), ('', 'p', 'at'), ('', 'q', 'at'), ('', 'r', 'at'), ('', 's', 'at'), ('', 't', 'at'), ('', 'u', 'at'), ('', 'v', 'at'), ('', 'w', 'at'), ('', 'x', 'at'), ('', 'y', 'at'), ('', 'z', 'at'), ('a', 'a', 't'), ('a', 'b', 't'), ('a', 'c', 't'), ('a', 'd', 't'), ('a', 'e', 't'), ('a', 'f', 't'), ('a', 'g', 't'), ('a', 'h', 't'), ('a', 'i', 't'), ('a', 'j', 't'), ('a', 'k', 't'), ('a', 'l', 't'), ('a', 'm', 't'), ('a', 'n', 't'), ('a', 'o', 't'), ('a', 'p', 't'), ('a', 'q', 't'), ('a', 'r', 't'), ('a', 's', 't'), ('a', 't', 't'), ('a', 'u', 't'), ('a', 'v', 't'), ('a', 'w', 't'), ('a', 'x', 't'), ('a', 'y', 't'), ('a', 'z', 't'), ('at', 'a', ''), ('at', 'b', ''), ('at', 'c', ''), ('at', 'd', ''), ('at', 'e', ''), ('at'

#### Expected output

```Python
Input word at
split_l = [('', 'at'), ('a', 't'), ('at', '')]
insert_l = ['aat', 'bat', 'cat', 'dat', 'eat', 'fat', 'gat', 'hat', 'iat', 'jat', 'kat', 'lat', 'mat', 'nat', 'oat', 'pat', 'qat', 'rat', 'sat', 'tat', 'uat', 'vat', 'wat', 'xat', 'yat', 'zat', 'aat', 'abt', 'act', 'adt', 'aet', 'aft', 'agt', 'aht', 'ait', 'ajt', 'akt', 'alt', 'amt', 'ant', 'aot', 'apt', 'aqt', 'art', 'ast', 'att', 'aut', 'avt', 'awt', 'axt', 'ayt', 'azt', 'ata', 'atb', 'atc', 'atd', 'ate', 'atf', 'atg', 'ath', 'ati', 'atj', 'atk', 'atl', 'atm', 'atn', 'ato', 'atp', 'atq', 'atr', 'ats', 'att', 'atu', 'atv', 'atw', 'atx', 'aty', 'atz']
Number of strings output by insert_letter('at') is 78
```

#### Note 1

If you get a split_l like this:
```Python
Input word at
split_l = [('', 'at'), ('a', 't')]
insert_l = ['aat', 'bat', 'cat', 'dat', 'eat', 'fat', 'gat', 'hat', 'iat', 'jat', 'kat', 'lat', 'mat', 'nat', 'oat', 'pat', 'qat', 'rat', 'sat', 'tat', 'uat', 'vat', 'wat', 'xat', 'yat', 'zat', 'aat', 'abt', 'act', 'adt', 'aet', 'aft', 'agt', 'aht', 'ait', 'ajt', 'akt', 'alt', 'amt', 'ant', 'aot', 'apt', 'aqt', 'art', 'ast', 'att', 'aut', 'avt', 'awt', 'axt', 'ayt', 'azt']
Number of strings output by insert_letter('at') is 52
```
- Notice that split_l is missing the extra tuple ('at', '').  For insertion, we actually **WANT** this tuple.
- The function is not creating all the desired output strings.
- Check the range that you use for the for loop.

#### Note 2
If you see this:
```Python
Input word at
split_l = [('', 'at'), ('a', 't'), ('at', '')]
insert_l = ['aat', 'bat', 'cat', 'dat', 'eat', 'fat', 'gat', 'hat', 'iat', 'jat', 'kat', 'lat', 'mat', 'nat', 'oat', 'pat', 'qat', 'rat', 'sat', 'tat', 'uat', 'vat', 'wat', 'xat', 'yat', 'zat', 'aat', 'abt', 'act', 'adt', 'aet', 'aft', 'agt', 'aht', 'ait', 'ajt', 'akt', 'alt', 'amt', 'ant', 'aot', 'apt', 'aqt', 'art', 'ast', 'att', 'aut', 'avt', 'awt', 'axt', 'ayt', 'azt']
Number of strings output by insert_letter('at') is 52
```

- Even though you may have fixed the split_l so that it contains the tuple `('at', '')`, notice that you're still missing some output strings.
    - Notice that it's missing strings such as 'ata', 'atb', 'atc' all the way to 'atz'.
- To fix this, make sure that when you set insert_l, you allow the use of the empty string `''`.

In [ ]:
# Unit-test for insert_letter
def test_insert_letter(target):
    failed_cases = []
    successful_cases = 0

    test_cases = [
        {
            "name": "default_check",
            "input": {"word": "at"},
            "expected": [
                "aat",
                "bat",
                "cat",
                "dat",
                "eat",
                "fat",
                "gat",
                "hat",
                "iat",
                "jat",
                "kat",
                "lat",
                "mat",
                "nat",
                "oat",
                "pat",
                "qat",
                "rat",
                "sat",
                "tat",
                "uat",
                "vat",
                "wat",
                "xat",
                "yat",
                "zat",
                "aat",
                "abt",
                "act",
                "adt",
                "aet",
                "aft",
                "agt",
                "aht",
                "ait",
                "ajt",
                "akt",
                "alt",
                "amt",
                "ant",
                "aot",
                "apt",
                "aqt",
                "art",
                "ast",
                "att",
                "aut",
                "avt",
                "awt",
                "axt",
                "ayt",
                "azt",
                "ata",
                "atb",
                "atc",
                "atd",
                "ate",
                "atf",
                "atg",
                "ath",
                "ati",
                "atj",
                "atk",
                "atl",
                "atm",
                "atn",
                "ato",
                "atp",
                "atq",
                "atr",
                "ats",
                "att",
                "atu",
                "atv",
                "atw",
                "atx",
                "aty",
                "atz",
            ],
        },
        {
            "name": "long_check",
            "input": {"word": "can"},
            "expected": [
                "acan",
                "bcan",
                "ccan",
                "dcan",
                "ecan",
                "fcan",
                "gcan",
                "hcan",
                "ican",
                "jcan",
                "kcan",
                "lcan",
                "mcan",
                "ncan",
                "ocan",
                "pcan",
                "qcan",
                "rcan",
                "scan",
                "tcan",
                "ucan",
                "vcan",
                "wcan",
                "xcan",
                "ycan",
                "zcan",
                "caan",
                "cban",
                "ccan",
                "cdan",
                "cean",
                "cfan",
                "cgan",
                "chan",
                "cian",
                "cjan",
                "ckan",
                "clan",
                "cman",
                "cnan",
                "coan",
                "cpan",
                "cqan",
                "cran",
                "csan",
                "ctan",
                "cuan",
                "cvan",
                "cwan",
                "cxan",
                "cyan",
                "czan",
                "caan",
                "cabn",
                "cacn",
                "cadn",
                "caen",
                "cafn",
                "cagn",
                "cahn",
                "cain",
                "cajn",
                "cakn",
                "caln",
                "camn",
                "cann",
                "caon",
                "capn",
                "caqn",
                "carn",
                "casn",
                "catn",
                "caun",
                "cavn",
                "cawn",
                "caxn",
                "cayn",
                "cazn",
                "cana",
                "canb",
                "canc",
                "cand",
                "cane",
                "canf",
                "cang",
                "canh",
                "cani",
                "canj",
                "cank",
                "canl",
                "canm",
                "cann",
                "cano",
                "canp",
                "canq",
                "canr",
                "cans",
                "cant",
                "canu",
                "canv",
                "canw",
                "canx",
                "cany",
                "canz",
            ],
        },
    ]

    for test_case in test_cases:
        result = target(**test_case["input"])

        try:
            assert isinstance(result, list)
            successful_cases += 1
        except:
            failed_cases.append(
                {"name": test_case["name"], "expected": list, "got": type(result)}
            )
            print(
                f"Wrong output type.\n\tExpected: {failed_cases[-1].get('expected')}.\n\tGot: {failed_cases[-1].get('got')}."
            )

        try:
            assert len(result) in [len(test_case["expected"]), len(set(test_case["expected"]))]
            successful_cases += 1
        except:
            failed_cases.append(
                {
                    "name": test_case["name"],
                    "expected": len(test_case["expected"]),
                    "got": len(result),
                }
            )
            print(
                f"Output list do not have the expected number of elements.\n\tExpected: {failed_cases[-1].get('expected')}.\n\tGot: {failed_cases[-1].get('got')}."
            )

        try:
            assert sorted(result) == sorted(test_case["expected"])
            successful_cases += 1
        except:
            failed_cases.append(
                {
                    "name": test_case["name"],
                    "expected": test_case["expected"],
                    "got": result,
                }
            )
            print(
                f"Wrong output values.\n\tExpected: {failed_cases[-1].get('expected')}.\n\tGot: {failed_cases[-1].get('got')}."
            )

    if len(failed_cases) == 0:
        print("\033[92m All tests passed")
    else:
        print("\033[92m", successful_cases, " Tests passed")
        print("\033[91m", len(failed_cases), " Tests failed")

In [ ]:
# Test your function
test_insert_letter(insert_letter)

 All tests passed


<a name='3'></a>
## 3 - Combining the Edits

Now that you have implemented the string manipulations, you will create two functions that, given a string, will return all the possible single and double edits on that string. These will be `edit_one_letter()` and `edit_two_letters()`.

<a name='3-1'></a>
### 3.1 - Edit One Letter

<a name='ex-8'></a>
### Exercise 8 - edit_one_letter

**Instructions**: Implement the `edit_one_letter` function to get all the possible edits that are one edit away from a word. The edits  consist of the replace, insert, delete, and optionally the switch operation. You should use the previous functions you have already implemented to complete this function. The 'switch' function  is a less common edit function, so its use will be selected by an "allow_switches" input argument.

Note that those functions return *lists* while this function should return a *python set*. Utilizing a set eliminates any duplicate entries.

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Hints</b></font>
</summary>
<p>
<ul>
    <li> Each of the functions returns a list.  You can combine lists using the `+` operator. </li>
    <li> To get unique strings (avoid duplicates), you can use the set() function. </li>
</ul>
</p>


In [ ]:
import string

def edit_one_letter(word, allow_switches = True):
    """
    Input:
        word: the string/word for which we will generate all possible wordsthat are one edit away.

    Output:
        edit_one_set: a set of words with one possible edit. Please return a set. and not a list.
    """

    edit_one_set = set()
    letters = string.ascii_lowercase  # All possible letters (a-z)

    ### START CODE HERE ###
    # Get all possible deletions
    for i in range(len(word)):
        delete_word = word[:i] + word[i+1:]  # Delete character at index i
        edit_one_set.add(delete_word)

    # Get all possible insertions
    for i in range(len(word) + 1):
        for c in letters:
            insert_word = word[:i] + c + word[i:]  # Insert character 'c' at index i
            edit_one_set.add(insert_word)

    # Get all possible replacements
    for i in range(len(word)):
        for c in letters:
            if word[i] != c:  # Replace the character at index i with 'c', only if different
                replace_word = word[:i] + c + word[i+1:]
                edit_one_set.add(replace_word)

    # Get all possible switches (if allowed)
    if allow_switches:
        for i in range(len(word) - 1):
            # Swap adjacent characters
            switch_word = word[:i] + word[i+1] + word[i] + word[i+2:]
            edit_one_set.add(switch_word)



    ### END CODE HERE ###

    # return this as a set and not a list

    return set(edit_one_set)

In [ ]:
tmp_word = "at"
tmp_edit_one_set = edit_one_letter(tmp_word)
# turn this into a list to sort it, in order to view it
tmp_edit_one_l = sorted(list(tmp_edit_one_set))

print(f"input word {tmp_word} \nedit_one_l \n{tmp_edit_one_l}\n")
print(f"The type of the returned object should be a set {type(tmp_edit_one_set)}")
print(f"Number of outputs from edit_one_letter('at') is {len(edit_one_letter('at'))}")

input word at 
edit_one_l 
['a', 'aa', 'aat', 'ab', 'abt', 'ac', 'act', 'ad', 'adt', 'ae', 'aet', 'af', 'aft', 'ag', 'agt', 'ah', 'aht', 'ai', 'ait', 'aj', 'ajt', 'ak', 'akt', 'al', 'alt', 'am', 'amt', 'an', 'ant', 'ao', 'aot', 'ap', 'apt', 'aq', 'aqt', 'ar', 'art', 'as', 'ast', 'ata', 'atb', 'atc', 'atd', 'ate', 'atf', 'atg', 'ath', 'ati', 'atj', 'atk', 'atl', 'atm', 'atn', 'ato', 'atp', 'atq', 'atr', 'ats', 'att', 'atu', 'atv', 'atw', 'atx', 'aty', 'atz', 'au', 'aut', 'av', 'avt', 'aw', 'awt', 'ax', 'axt', 'ay', 'ayt', 'az', 'azt', 'bat', 'bt', 'cat', 'ct', 'dat', 'dt', 'eat', 'et', 'fat', 'ft', 'gat', 'gt', 'hat', 'ht', 'iat', 'it', 'jat', 'jt', 'kat', 'kt', 'lat', 'lt', 'mat', 'mt', 'nat', 'nt', 'oat', 'ot', 'pat', 'pt', 'qat', 'qt', 'rat', 'rt', 'sat', 'st', 't', 'ta', 'tat', 'tt', 'uat', 'ut', 'vat', 'vt', 'wat', 'wt', 'xat', 'xt', 'yat', 'yt', 'zat', 'zt']

The type of the returned object should be a set <class 'set'>
Number of outputs from edit_one_letter('at') is 129


#### Expected Output
```CPP
input word at
edit_one_l
['a', 'aa', 'aat', 'ab', 'abt', 'ac', 'act', 'ad', 'adt', 'ae', 'aet', 'af', 'aft', 'ag', 'agt', 'ah', 'aht', 'ai', 'ait', 'aj', 'ajt', 'ak', 'akt', 'al', 'alt', 'am', 'amt', 'an', 'ant', 'ao', 'aot', 'ap', 'apt', 'aq', 'aqt', 'ar', 'art', 'as', 'ast', 'ata', 'atb', 'atc', 'atd', 'ate', 'atf', 'atg', 'ath', 'ati', 'atj', 'atk', 'atl', 'atm', 'atn', 'ato', 'atp', 'atq', 'atr', 'ats', 'att', 'atu', 'atv', 'atw', 'atx', 'aty', 'atz', 'au', 'aut', 'av', 'avt', 'aw', 'awt', 'ax', 'axt', 'ay', 'ayt', 'az', 'azt', 'bat', 'bt', 'cat', 'ct', 'dat', 'dt', 'eat', 'et', 'fat', 'ft', 'gat', 'gt', 'hat', 'ht', 'iat', 'it', 'jat', 'jt', 'kat', 'kt', 'lat', 'lt', 'mat', 'mt', 'nat', 'nt', 'oat', 'ot', 'pat', 'pt', 'qat', 'qt', 'rat', 'rt', 'sat', 'st', 't', 'ta', 'tat', 'tt', 'uat', 'ut', 'vat', 'vt', 'wat', 'wt', 'xat', 'xt', 'yat', 'yt', 'zat', 'zt']

The type of the returned object should be a set <class 'set'>
Number of outputs from edit_one_letter('at') is 129
```

In [ ]:
# Unit-tests for edit_one_letter
def test_edit_one_letter(target):
    failed_cases = []
    successful_cases = 0

    test_cases = [
        {
            "name": "default_check",
            "input": {"word": "at"},
            "expected": set(
                [
                    "a",
                    "aa",
                    "aat",
                    "ab",
                    "abt",
                    "ac",
                    "act",
                    "ad",
                    "adt",
                    "ae",
                    "aet",
                    "af",
                    "aft",
                    "ag",
                    "agt",
                    "ah",
                    "aht",
                    "ai",
                    "ait",
                    "aj",
                    "ajt",
                    "ak",
                    "akt",
                    "al",
                    "alt",
                    "am",
                    "amt",
                    "an",
                    "ant",
                    "ao",
                    "aot",
                    "ap",
                    "apt",
                    "aq",
                    "aqt",
                    "ar",
                    "art",
                    "as",
                    "ast",
                    "ata",
                    "atb",
                    "atc",
                    "atd",
                    "ate",
                    "atf",
                    "atg",
                    "ath",
                    "ati",
                    "atj",
                    "atk",
                    "atl",
                    "atm",
                    "atn",
                    "ato",
                    "atp",
                    "atq",
                    "atr",
                    "ats",
                    "att",
                    "atu",
                    "atv",
                    "atw",
                    "atx",
                    "aty",
                    "atz",
                    "au",
                    "aut",
                    "av",
                    "avt",
                    "aw",
                    "awt",
                    "ax",
                    "axt",
                    "ay",
                    "ayt",
                    "az",
                    "azt",
                    "bat",
                    "bt",
                    "cat",
                    "ct",
                    "dat",
                    "dt",
                    "eat",
                    "et",
                    "fat",
                    "ft",
                    "gat",
                    "gt",
                    "hat",
                    "ht",
                    "iat",
                    "it",
                    "jat",
                    "jt",
                    "kat",
                    "kt",
                    "lat",
                    "lt",
                    "mat",
                    "mt",
                    "nat",
                    "nt",
                    "oat",
                    "ot",
                    "pat",
                    "pt",
                    "qat",
                    "qt",
                    "rat",
                    "rt",
                    "sat",
                    "st",
                    "t",
                    "ta",
                    "tat",
                    "tt",
                    "uat",
                    "ut",
                    "vat",
                    "vt",
                    "wat",
                    "wt",
                    "xat",
                    "xt",
                    "yat",
                    "yt",
                    "zat",
                    "zt",
                ]
            ),
        },
        {
            "name": "long_check_allow_switches_true",
            "input": {"word": "can", "allow_switches":True},
            "expected": set(
                [
                    "aan",
                    "acan",
                    "acn",
                    "an",
                    "ban",
                    "bcan",
                    "ca",
                    "caa",
                    "caan",
                    "cab",
                    "cabn",
                    "cac",
                    "cacn",
                    "cad",
                    "cadn",
                    "cae",
                    "caen",
                    "caf",
                    "cafn",
                    "cag",
                    "cagn",
                    "cah",
                    "cahn",
                    "cai",
                    "cain",
                    "caj",
                    "cajn",
                    "cak",
                    "cakn",
                    "cal",
                    "caln",
                    "cam",
                    "camn",
                    "cana",
                    "canb",
                    "canc",
                    "cand",
                    "cane",
                    "canf",
                    "cang",
                    "canh",
                    "cani",
                    "canj",
                    "cank",
                    "canl",
                    "canm",
                    "cann",
                    "cano",
                    "canp",
                    "canq",
                    "canr",
                    "cans",
                    "cant",
                    "canu",
                    "canv",
                    "canw",
                    "canx",
                    "cany",
                    "canz",
                    "cao",
                    "caon",
                    "cap",
                    "capn",
                    "caq",
                    "caqn",
                    "car",
                    "carn",
                    "cas",
                    "casn",
                    "cat",
                    "catn",
                    "cau",
                    "caun",
                    "cav",
                    "cavn",
                    "caw",
                    "cawn",
                    "cax",
                    "caxn",
                    "cay",
                    "cayn",
                    "caz",
                    "cazn",
                    "cban",
                    "cbn",
                    "ccan",
                    "ccn",
                    "cdan",
                    "cdn",
                    "cean",
                    "cen",
                    "cfan",
                    "cfn",
                    "cgan",
                    "cgn",
                    "chan",
                    "chn",
                    "cian",
                    "cin",
                    "cjan",
                    "cjn",
                    "ckan",
                    "ckn",
                    "clan",
                    "cln",
                    "cman",
                    "cmn",
                    "cn",
                    "cna",
                    "cnan",
                    "cnn",
                    "coan",
                    "con",
                    "cpan",
                    "cpn",
                    "cqan",
                    "cqn",
                    "cran",
                    "crn",
                    "csan",
                    "csn",
                    "ctan",
                    "ctn",
                    "cuan",
                    "cun",
                    "cvan",
                    "cvn",
                    "cwan",
                    "cwn",
                    "cxan",
                    "cxn",
                    "cyan",
                    "cyn",
                    "czan",
                    "czn",
                    "dan",
                    "dcan",
                    "ean",
                    "ecan",
                    "fan",
                    "fcan",
                    "gan",
                    "gcan",
                    "han",
                    "hcan",
                    "ian",
                    "ican",
                    "jan",
                    "jcan",
                    "kan",
                    "kcan",
                    "lan",
                    "lcan",
                    "man",
                    "mcan",
                    "nan",
                    "ncan",
                    "oan",
                    "ocan",
                    "pan",
                    "pcan",
                    "qan",
                    "qcan",
                    "ran",
                    "rcan",
                    "san",
                    "scan",
                    "tan",
                    "tcan",
                    "uan",
                    "ucan",
                    "van",
                    "vcan",
                    "wan",
                    "wcan",
                    "xan",
                    "xcan",
                    "yan",
                    "ycan",
                    "zan",
                    "zcan",
                ]
            ),
        },
        {
            "name": "long_check_allow_switches_false",
            "input": {"word": "can", 'allow_switches': False},
            "expected": set(
                [
                    'aan',
                    'acan',
                    'an',
                    'ban',
                    'bcan',
                    'ca',
                    'caa',
                    'caan',
                    'cab',
                    'cabn',
                    'cac',
                    'cacn',
                    'cad',
                    'cadn',
                    'cae',
                    'caen',
                    'caf',
                    'cafn',
                    'cag',
                    'cagn',
                    'cah',
                    'cahn',
                    'cai',
                    'cain',
                    'caj',
                    'cajn',
                    'cak',
                    'cakn',
                    'cal',
                    'caln',
                    'cam',
                    'camn',
                    'cana',
                    'canb',
                    'canc',
                    'cand',
                    'cane',
                    'canf',
                    'cang',
                    'canh',
                    'cani',
                    'canj',
                    'cank',
                    'canl',
                    'canm',
                    'cann',
                    'cano',
                    'canp',
                    'canq',
                    'canr',
                    'cans',
                    'cant',
                    'canu',
                    'canv',
                    'canw',
                    'canx',
                    'cany',
                    'canz',
                    'cao',
                    'caon',
                    'cap',
                    'capn',
                    'caq',
                    'caqn',
                    'car',
                    'carn',
                    'cas',
                    'casn',
                    'cat',
                    'catn',
                    'cau',
                    'caun',
                    'cav',
                    'cavn',
                    'caw',
                    'cawn',
                    'cax',
                    'caxn',
                    'cay',
                    'cayn',
                    'caz',
                    'cazn',
                    'cban',
                    'cbn',
                    'ccan',
                    'ccn',
                    'cdan',
                    'cdn',
                    'cean',
                    'cen',
                    'cfan',
                    'cfn',
                    'cgan',
                    'cgn',
                    'chan',
                    'chn',
                    'cian',
                    'cin',
                    'cjan',
                    'cjn',
                    'ckan',
                    'ckn',
                    'clan',
                    'cln',
                    'cman',
                    'cmn',
                    'cn',
                    'cnan',
                    'cnn',
                    'coan',
                    'con',
                    'cpan',
                    'cpn',
                    'cqan',
                    'cqn',
                    'cran',
                    'crn',
                    'csan',
                    'csn',
                    'ctan',
                    'ctn',
                    'cuan',
                    'cun',
                    'cvan',
                    'cvn',
                    'cwan',
                    'cwn',
                    'cxan',
                    'cxn',
                    'cyan',
                    'cyn',
                    'czan',
                    'czn',
                    'dan',
                    'dcan',
                    'ean',
                    'ecan',
                    'fan',
                    'fcan',
                    'gan',
                    'gcan',
                    'han',
                    'hcan',
                    'ian',
                    'ican',
                    'jan',
                    'jcan',
                    'kan',
                    'kcan',
                    'lan',
                    'lcan',
                    'man',
                    'mcan',
                    'nan',
                    'ncan',
                    'oan',
                    'ocan',
                    'pan',
                    'pcan',
                    'qan',
                    'qcan',
                    'ran',
                    'rcan',
                    'san',
                    'scan',
                    'tan',
                    'tcan',
                    'uan',
                    'ucan',
                    'van',
                    'vcan',
                    'wan',
                    'wcan',
                    'xan',
                    'xcan',
                    'yan',
                    'ycan',
                    'zan',
                    'zcan'
                ]
            ),
        }
    ]

    for test_case in test_cases:
        result = target(**test_case["input"])

        try:
            assert isinstance(result, set)
            successful_cases += 1
        except:
            failed_cases.append(
                {"name": test_case["name"], "expected": set, "got": type(result)}
            )
            print(
                f"Wrong output type.\n\tExpected: {failed_cases[-1].get('expected')}.\n\tGot: {failed_cases[-1].get('got')}."
            )

        try:
            assert len(result) == len(test_case["expected"])
            successful_cases += 1
        except:
            failed_cases.append(
                {
                    "name": test_case["name"],
                    "expected": len(test_case["expected"]),
                    "got": len(result),
                }
            )
            print(
                f"Wrong number of elements in the returned set.\n\tExpected: {failed_cases[-1].get('expected')}.\n\tGot: {failed_cases[-1].get('got')}."
            )

        try:
            assert sorted(result) == sorted(test_case["expected"])
            successful_cases += 1
        except:
            failed_cases.append(
                {
                    "name": test_case["name"],
                    "expected": test_case["expected"],
                    "got": result,
                }
            )
            print(
                f"Wrong output values.\n\tExpected: {failed_cases[-1].get('expected')}.\n\tGot: {failed_cases[-1].get('got')}."
            )

    if len(failed_cases) == 0:
        print("\033[92m All tests passed")
    else:
        print("\033[92m", successful_cases, " Tests passed")
        print("\033[91m", len(failed_cases), " Tests failed")

In [ ]:
# Test your function
test_edit_one_letter(edit_one_letter)

 All tests passed


<a name='3-2'></a>
### 3.2 - Edit Two Letters

<a name='ex-9'></a>
### Exercise 9 - edit_two_letters

Now you can generalize this to implement to get two edits on a word. To do so, you would have to get all the possible edits on a single word and then for each modified word, you would have to modify it again.

**Instructions**: Implement the `edit_two_letters` function that returns a set of words that are two edits away. Note that creating additional edits based on the `edit_one_letter` function may 'restore' some one_edits to zero or one edits. That is allowed here. This is accounted for in get_corrections.

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Hints</b></font>
</summary>
<p>
<ul>
    <li>You will likely want to take the union of two sets.</li>
    <li>You can either use set.update() or use the '|' (or operator) to union two sets</li>
    <li>See the documentation <a href="https://docs.python.org/2/library/sets.html" > Python sets </a> for examples of using operators or functions of the Python set.</li>
</ul>
</p>


In [ ]:
def edit_two_letters(word, allow_switches = True):
    """
    Input:
        word: the input string/word
    Output:
        edit_two_set: a set of strings with all possible two edits
    """
    one_edit_set = edit_one_letter(word, allow_switches)

    edit_two_set = set()

    ### START CODE HERE ###
        # Step 3: For each word in the one-edit set, apply edit_one_letter again to get two edits
    for one_edit_word in one_edit_set:
        # Generate one-edit variations of each one-edit word (this results in two edits)
        second_edit_set = edit_one_letter(one_edit_word, allow_switches)

        # Add the results of two edits to the final set
        edit_two_set.update(second_edit_set)

    ### END CODE HERE ###

    # return this as a set instead of a list
    return set(edit_two_set)

In [ ]:
tmp_edit_two_set = edit_two_letters("a")
tmp_edit_two_l = sorted(list(tmp_edit_two_set))
print(f"Number of strings with edit distance of two: {len(tmp_edit_two_l)}")
print(f"First 10 strings {tmp_edit_two_l[:10]}")
print(f"Last 10 strings {tmp_edit_two_l[-10:]}")
print(f"The data type of the returned object should be a set {type(tmp_edit_two_set)}")
print(f"Number of strings that are 2 edit distances from 'at' is {len(edit_two_letters('at'))}")

Number of strings with edit distance of two: 2654
First 10 strings ['', 'a', 'aa', 'aaa', 'aab', 'aac', 'aad', 'aae', 'aaf', 'aag']
Last 10 strings ['zv', 'zva', 'zw', 'zwa', 'zx', 'zxa', 'zy', 'zya', 'zz', 'zza']
The data type of the returned object should be a set <class 'set'>
Number of strings that are 2 edit distances from 'at' is 7154


#### Expected Output

```CPP
Number of strings with edit distance of two: 2654
First 10 strings ['', 'a', 'aa', 'aaa', 'aab', 'aac', 'aad', 'aae', 'aaf', 'aag']
Last 10 strings ['zv', 'zva', 'zw', 'zwa', 'zx', 'zxa', 'zy', 'zya', 'zz', 'zza']
The data type of the returned object should be a set <class 'set'>
Number of strings that are 2 edit distances from 'at' is 7154
```

In [ ]:
# Unit-tests for edit_two_letter
def test_edit_two_letters(target):
    failed_cases = []
    successful_cases = 0

    test_cases = [
        {
            "name": "default_check1",
            "input": {"word": "a"},
            "expected": {
                "expected_n_words_edit_dist": 2654,
                "expected_head": [
                    "",
                    "a",
                    "aa",
                    "aaa",
                    "aab",
                    "aac",
                    "aad",
                    "aae",
                    "aaf",
                    "aag",
                ],
                "expected_tail": [
                    "zv",
                    "zva",
                    "zw",
                    "zwa",
                    "zx",
                    "zxa",
                    "zy",
                    "zya",
                    "zz",
                    "zza",
                ],
            },
        },
        {
            "name": "default_check2",
            "input": {"word": "at"},
            "expected": {
                "expected_n_words_edit_dist": 7154,
                "expected_head": [
                    "",
                    "a",
                    "aa",
                    "aaa",
                    "aaat",
                    "aab",
                    "aabt",
                    "aac",
                    "aact",
                    "aad",
                ],
                "expected_tail": [
                    "zwt",
                    "zx",
                    "zxat",
                    "zxt",
                    "zy",
                    "zyat",
                    "zyt",
                    "zz",
                    "zzat",
                    "zzt",
                ],
            },
        },
        {
            "name": "switches_check",
            "input": {"word": "at", "allow_switches": False},
            "expected": {
                "expected_n_words_edit_dist": 7130,
                "expected_head": [
                    "",
                    "a",
                    "aa",
                    "aaa",
                    "aaat",
                    "aab",
                    "aabt",
                    "aac",
                    "aact",
                    "aad",
                ],
                "expected_tail": [
                    "zwt",
                    "zx",
                    "zxat",
                    "zxt",
                    "zy",
                    "zyat",
                    "zyt",
                    "zz",
                    "zzat",
                    "zzt",
                ],
            },
        },
        {
            "name": "long_check_no_switch",
            "input": {"word": "cat", "allow_switches": False},
            "expected": {
                "expected_n_words_edit_dist": 14206,
                "expected_head": [
                    "a",
                    "aa",
                    "aaa",
                    "aaat",
                    "aab",
                    "aabt",
                    "aac",
                    "aacat",
                    "aact",
                    "aad",
                ],
                "expected_tail": [
                    "zwt",
                    "zxat",
                    "zxcat",
                    "zxt",
                    "zyat",
                    "zycat",
                    "zyt",
                    "zzat",
                    "zzcat",
                    "zzt",
                ],
            },
        },
        {
            "name": "long_check_switch",
            "input": {"word": "cat"},
            "expected": {
                "expected_n_words_edit_dist": 14352,
                "expected_head": [
                    "a",
                    "aa",
                    "aaa",
                    "aaat",
                    "aab",
                    "aabt",
                    "aac",
                    "aacat",
                    "aact",
                    "aad",
                ],
                "expected_tail": [
                    "zwt",
                    "zxat",
                    "zxcat",
                    "zxt",
                    "zyat",
                    "zycat",
                    "zyt",
                    "zzat",
                    "zzcat",
                    "zzt",
                ],
            },
        },
    ]

    for test_case in test_cases:
        result = target(**test_case["input"])

        try:
            assert isinstance(result, set)
            successful_cases += 1
        except:
            failed_cases.append(
                {"name": test_case["name"], "expected": set, "got": type(result),}
            )
            print(
                f"Wrong output type.\n\tExpected: {failed_cases[-1].get('expected')}.\n\tGot: {failed_cases[-1].get('got')}."
            )

        try:
            assert len(result) == test_case["expected"]["expected_n_words_edit_dist"]
            successful_cases += 1
        except:
            failed_cases.append(
                {
                    "name": test_case["name"],
                    "expected": test_case["expected"]["expected_n_words_edit_dist"],
                    "got": len(result),
                }
            )
            print(
                f"Wrong output type.\n\tExpected: {failed_cases[-1].get('expected')}.\n\tGot: {failed_cases[-1].get('got')}."
            )

        try:
            assert sorted(list(result))[:10] == sorted(
                test_case["expected"]["expected_head"]
            )
            successful_cases += 1
        except:
            failed_cases.append(
                {
                    "name": test_case["name"],
                    "expected": test_case["expected"]["expected_head"],
                    "got": list(result)[:10],
                }
            )
            print(
                f"First ten output values are wrong.\n\tExpected: {failed_cases[-1].get('expected')}.\n\tGot: {failed_cases[-1].get('got')}."
            )

        try:
            assert sorted(list(result))[-10:] == sorted(
                test_case["expected"]["expected_tail"]
            )
            successful_cases += 1
        except:
            failed_cases.append(
                {
                    "name": test_case["name"],
                    "expected": test_case["expected"]["expected_tail"],
                    "got": list(result)[:10],
                }
            )
            print(
                f"Last ten output values are wrong.\n\tExpected: {failed_cases[-1].get('expected')}.\n\tGot: {failed_cases[-1].get('got')}."
            )

    if len(failed_cases) == 0:
        print("\033[92m All tests passed")
    else:
        print("\033[92m", successful_cases, " Tests passed")
        print("\033[91m", len(failed_cases), " Tests failed")

In [ ]:
# Test your function
test_edit_two_letters(edit_two_letters)

 All tests passed


<a name='3-3'></a>
### 3.3 - Suggest Spelling Suggestions

Now you will use your `edit_two_letters` function to get a set of all the possible 2 edits on your word. You will then use those strings to get the most probable word you meant to type a.k.a your typing suggestion.

<a name='ex-10'></a>
### Exercise 10 - get_corrections
**Instructions**: Implement `get_corrections`, which returns a list of zero to n possible suggestion tuples of the form (word, probability_of_word).

**Step 1:** Generate suggestions for a supplied word: You'll use the edit functions you have developed. The 'suggestion algorithm' should follow this logic:
* If the word is in the vocabulary, suggest the word.
* Otherwise, if there are suggestions from `edit_one_letter` that are in the vocabulary, use those.
* Otherwise, if there are suggestions from `edit_two_letters` that are in the vocabulary, use those.
* Otherwise, suggest the input word.*  
* The idea is that words generated from fewer edits are more likely than words with more edits.


Note:
- Edits of two letters may 'restore' strings to either zero or one edit. This algorithm accounts for this by preferentially selecting lower distance edits first.

#### Short circuit
In Python, logical operations such as `and` and `or` have two useful properties. They can operate on lists and they have ['short-circuit' behavior](https://docs.python.org/3/library/stdtypes.html). Try these:

In [ ]:
# example of logical operation on lists or sets
print( [] and ["a","b"] )
print( [] or ["a","b"] )
#example of Short circuit behavior
val1 =  ["Most","Likely"] or ["Less","so"] or ["least","of","all"]  # selects first, does not evalute remainder
print(val1)
val2 =  [] or [] or ["least","of","all"] # continues evaluation until there is a non-empty list
print(val2)

[]
['a', 'b']
['Most', 'Likely']
['least', 'of', 'all']


Use the logical `or` to implement the suggestion algorithm very compactly.

**Step 2**: Create a 'best_words' dictionary where the 'key' is a suggestion and the 'value' is the probability of that word in your vocabulary. If the word is not in the vocabulary, assign it a probability of 0.

**Step 3**: Select the n best suggestions. There may be fewer than n.

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Hints</b></font>
</summary>
<p>
<ul>
    <li>edit_one_letter and edit_two_letters return *python sets*. </li>
    <li> Sets have a handy <a href="https://docs.python.org/2/library/sets.html" > set.intersection </a> feature</li>
    <li>To find the keys that have the highest values in a dictionary, you can use the Counter dictionary to create a Counter object from a regular dictionary.  Then you can use Counter.most_common(n) to get the n most common keys.
    </li>
    <li>To find the intersection of two sets, you can use set.intersection or the & operator.</li>
    <li>If you are not as familiar with short circuit syntax (as shown above), feel free to use if else statements instead.</li>
    <li>To use an if statement to check of a set is empty, use 'if not x:' syntax </li>
</ul>
</p>


In [ ]:
def get_corrections(word, probs, vocab, n=2, verbose = False):
    """
    Input:
        word: a user entered string to check for suggestions
        probs: a dictionary that maps each word to its probability in the corpus
        vocab: a set containing all the vocabulary
        n: number of possible word corrections you want returned in the dictionary
    Output:
        n_best: a list of tuples with the most probable n corrected words and their probabilities.
    """

    suggestions = []
    n_best = []

    ### START CODE HERE ###
    #Step 1: create suggestions as described above
    # If word is in vocab, suggest it; otherwise, get suggestions from edit_one_letter and edit_two_letters

    suggestions = (
        [word] if word in vocab  # If the word is in vocab, it is the best suggestion
        else [w for w in edit_one_letter(word) if w in vocab]  # Try one-edit words
        or [w for w in edit_two_letters(word) if w in vocab]  # Try two-edit words
        or [word]  # If nothing works, return the original word as a fallback
    )


    #Step 2: determine probability of suggestions
    # For each suggestion, get its probability from the probs dictionary (default to 0 if not found)
    best_words = {w: probs.get(w, 0) for w in suggestions}

    #Step 3: Get all your best words and return the most probable top n_suggested words as n_best

    n_best = sorted(best_words.items(), key=lambda x: x[1], reverse=True)[:n]

    if verbose:
        print("Entered word =", word)
        print("Suggestions =", suggestions)

    return n_best



    ### END CODE HERE ###



In [ ]:
# Test your implementation - feel free to try other words in my word
my_word = 'dys'
tmp_corrections = get_corrections(my_word, probs, vocab, 2, verbose=True) # keep verbose=True
for i, word_prob in enumerate(tmp_corrections):
    print(f"word {i}: {word_prob[0]}, probability {word_prob[1]:.6f}")

print(f"data type of corrections {type(tmp_corrections)}")

Entered word = dys
Suggestions = ['days', 'dye']
word 0: days, probability 0.000422
word 1: dye, probability 0.000019
data type of corrections <class 'list'>


#### Expected Output
- Note: This expected output is for `my_word = 'dys'`. Also, keep `verbose=True`
```CPP
entered word =  dys
suggestions =  {'days', 'dye'}
word 0: days, probability 0.000410
word 1: dye, probability 0.000019
data type of corrections <class 'list'>
```

In [ ]:
# Unit-tests for get_corrections
def test_get_corrections(target, probs, vocab):
    failed_cases = []
    successful_cases = 0

    test_cases = [
        {
            "name": "default_check",
            "input": {"word": "dys", "probs": probs, "vocab": vocab, "n": 2},
            "expected": {
                "n_best": [
                    ("days", 0.0004103405826836274),
                    ("dye", 1.865184466743761e-5),
                ]
            },
        },
        {
            "name": "default_check",
            "input": {"word": "satr", "probs": probs, "vocab": vocab, "n": 2},
            "expected": {
                "n_best": [
                    ("star", 0.00013056291267206328),
                    ("sat", 5.595553400231283e-05),
                ]
            },
        },
        {
            "name": "default_check",
            "input": {"word": "san", "probs": probs, "vocab": vocab, "n": 5},
            "expected": {
                "n_best": [
                    ("say", 0.0019770955347483865),
                    ("can", 0.0019211400007460738),
                    ("an", 0.0017719252434065728),
                    ("man", 0.0013242809713880702),
                    ("son", 0.0007274219420300668),
                ]
            },
        },
    ]

    for test_case in test_cases:
        result = target(**test_case["input"])

        try:
            assert isinstance(result, list)
            successful_cases += 1
        except:
            failed_cases.append(
                {"name": test_case["name"], "expected": list, "got": type(result),}
            )
            print(
                f"Wrong output type.\n\tExpected: {failed_cases[-1].get('expected')}.\n\tGot: {failed_cases[-1].get('got')}."
            )

        try:
            assert len(result) == len(test_case["expected"]["n_best"])
            successful_cases += 1
        except:
            failed_cases.append(
                {
                    "name": test_case["name"],
                    "expected": len(test_case["expected"]["n_best"]),
                    "got": len(result),
                }
            )
            print(
                f"Wrong output length.\n\tExpected: {failed_cases[-1].get('expected')}.\n\tGot: {failed_cases[-1].get('got')}."
            )

        try:
            for index, elem in enumerate(sorted(result)):
                assert elem[0] == sorted(test_case["expected"]["n_best"])[index][0]
                assert np.isclose(
                    elem[1], sorted(test_case["expected"]["n_best"])[index][1]
                )
            successful_cases += 1
        except:
            failed_cases.append(
                {
                    "name": test_case["name"],
                    "expected": test_case["expected"]["n_best"],
                    "got": result,
                }
            )
            print(
                f"Wrong output values.\n\tExpected: {failed_cases[-1].get('expected')}.\n\tGot: {failed_cases[-1].get('got')}."
            )

    if len(failed_cases) == 0:
        print("\033[92m All tests passed")
    else:
        print("\033[92m", successful_cases, " Tests passed")
        print("\033[91m", len(failed_cases), " Tests failed")

In [ ]:
# Test your function
test_get_corrections(get_corrections, probs, vocab)

Wrong output values.
	Expected: [('days', 0.0004103405826836274), ('dye', 1.865184466743761e-05)].
	Got: [('days', 0.0004217710550027799), ('dye', 1.9171411591035448e-05)].
Wrong output values.
	Expected: [('star', 0.00013056291267206328), ('sat', 5.595553400231283e-05)].
	Got: [('star', 0.00013419988113724815), ('sat', 5.751423477310634e-05)].
Wrong output values.
	Expected: [('say', 0.0019770955347483865), ('can', 0.0019211400007460738), ('an', 0.0017719252434065728), ('man', 0.0013242809713880702), ('son', 0.0007274219420300668)].
	Got: [('say', 0.0019938268054676867), ('can', 0.0019363125706945803), ('an', 0.001802112689557332), ('man', 0.0011886275186441977), ('son', 0.0007093422288683115)].
 6  Tests passed
 3  Tests failed


<a name='4'></a>
## 4 - Minimum Edit Distance

Now that you have implemented your auto-correct, how do you evaluate the similarity between two strings? For example: 'waht' and 'what'

Also how do you efficiently find the shortest path to go from the word, 'waht' to the word 'what'?

You will implement a dynamic programming system that will tell you the minimum number of edits required to convert a string into another string.

<a name='4-1'></a>
### 4.1 - Dynamic Programming

Dynamic Programming breaks a problem down into subproblems which can be combined to form the final solution. Here, given a string source[0..i] and a string target[0..j], we will compute all the combinations of substrings[i, j] and calculate their edit distance. To do this efficiently, we will use a table to maintain the previously computed substrings and use those to calculate larger substrings.

You have to create a matrix and update each element in the matrix as follows:  

$$\text{Initialization}$$

\begin{align}
D[0,0] &= 0 \\
D[i,0] &= D[i-1,0] + del\_cost(source[i]) \tag{4}\\
D[0,j] &= D[0,j-1] + ins\_cost(target[j]) \\
\end{align}


$$\text{Per Cell Operations}$$
\begin{align}
 \\
D[i,j] =min
\begin{cases}
D[i-1,j] + del\_cost\\
D[i,j-1] + ins\_cost\\
D[i-1,j-1] + \left\{\begin{matrix}
rep\_cost; & if src[i]\neq tar[j]\\
0 ; & if src[i]=tar[j]
\end{matrix}\right.
\end{cases}
\tag{5}
\end{align}

So converting the source word **play** to the target word **stay**, using an input cost of one, a delete cost of 1, and replace cost of 2 would give you the following table:
<table style="width:20%">

  <tr>
    <td> <b> </b>  </td>
    <td> <b># </b>  </td>
    <td> <b>s </b>  </td>
    <td> <b>t </b> </td>
    <td> <b>a </b> </td>
    <td> <b>y </b> </td>
  </tr>
   <tr>
    <td> <b>  #  </b></td>
    <td> 0</td>
    <td> 1</td>
    <td> 2</td>
    <td> 3</td>
    <td> 4</td>

  </tr>
  <tr>
    <td> <b>  p  </b></td>
    <td> 1</td>
 <td> 2</td>
    <td> 3</td>
    <td> 4</td>
   <td> 5</td>
  </tr>
   
  <tr>
    <td> <b> l </b></td>
    <td>2</td>
    <td>3</td>
    <td>4</td>
    <td>5</td>
    <td>6</td>
  </tr>

  <tr>
    <td> <b> a </b></td>
    <td>3</td>
     <td>4</td>
     <td>5</td>
     <td>4</td>
     <td>5</td>
  </tr>
  
   <tr>
    <td> <b> y </b></td>
    <td>4</td>
      <td>5</td>
     <td>6</td>
     <td>5</td>
     <td>4</td>
  </tr>
  

</table>



The operations used in this algorithm are 'insert', 'delete', and 'replace'. These correspond to the functions that you defined earlier: insert_letter(), delete_letter() and replace_letter(). switch_letter() is not used here.

The diagram below describes how to initialize the table. Each entry in D[i,j] represents the minimum cost of converting string source[0:i] to string target[0:j]. The first column is initialized to represent the cumulative cost of deleting the source characters to convert string "EER" to "". The first row is initialized to represent the cumulative cost of inserting the target characters to convert from "" to "NEAR".

<div style="width:image width px; font-size:100%; text-align:center;"><img src='https://drive.google.com/uc?export&id=1LbizBPiNBKqhHWpXBpasDLkse5LXCjpb' alt="alternate text" width="width" height="height" style="width:1000px;height:400px;"/> Figure 6 Initializing Distance Matrix</div>     

Filling in the remainder of the table utilizes the 'Per Cell Operations' in the equation (5) above. Note, the diagram below includes in the table some of the 3 sub-calculations shown in light grey. Only 'min' of those operations is stored in the table in the `min_edit_distance()` function.

<div style="width:image width px; font-size:100%; text-align:center;"><img src='https://drive.google.com/uc?export&id=1b2Uj_GsAOf0azJymwRrZCTVwW3Pm--lu' alt="alternate text" width="width" height="height" style="width:800px;height:400px;"/> Figure 7 Filling Distance Matrix</div>     

Note that the formula for $D[i,j]$ shown in the image is equivalent to:

\begin{align}
 \\
D[i,j] =min
\begin{cases}
D[i-1,j] + del\_cost\\
D[i,j-1] + ins\_cost\\
D[i-1,j-1] + \left\{\begin{matrix}
rep\_cost; & if src[i]\neq tar[j]\\
0 ; & if src[i]=tar[j]
\end{matrix}\right.
\end{cases}
\tag{5}
\end{align}

The variable `sub_cost` (for substitution cost) is the same as `rep_cost`; replacement cost.  We will stick with the term "replace" whenever possible.

Below are some examples of cells where replacement is used. This also shows the minimum path from the lower right final position where "EER" has been replaced by "NEAR" back to the start. This provides a starting point for the optional 'backtrace' algorithm below.

<div style="width:image width px; font-size:100%; text-align:center;"><img src='https://drive.google.com/uc?export&id=1UEOh_mL3cIpBUVy8ZGBEYMjkQyEP9okG' alt="alternate text" width="width" height="height" style="width:1200px;height:400px;"/> Figure 8 Examples Distance Matrix</div>    

<a name='ex-11'></a>
### Exercise 11 - min_edit_distance

Again, the word "substitution" appears in the figure, but think of this as "replacement".

**Instructions**: Implement the function below to get the minimum amount of edits required given a source string and a target string.

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Hints</b></font>
</summary>
<p>
<ul>
    <li>The range(start, stop, step) function excludes 'stop' from its output</li>
    <li><a href="" > words </a> </li>
</ul>
</p>


In [ ]:

def min_edit_distance(source, target, ins_cost = 1, del_cost = 1, rep_cost = 2):
    """
    Input:
        source: a string corresponding to the string you are starting with
        target: a string corresponding to the string you want to end with
        ins_cost: an integer setting the insert cost
        del_cost: an integer setting the delete cost
        rep_cost: an integer setting the replace cost
    Output:
        D: a matrix of len(source)+1 by len(target)+1 containing minimum edit distances
        med: the minimum edit distance (med) required to convert the source string to the target
    """
    # use deletion and insert cost as  1
    m = len(source)
    n = len(target)
    #initialize cost matrix with zeros and dimensions (m+1,n+1)
    D = np.zeros((m+1, n+1), dtype=int)

    ### START CODE HERE (Replace instances of 'None' with your code) ###

    # Fill in column 0, from row 1 to row m, both inclusive
    for row in range(1, m+1): # Replace None with the proper range
        D[row,0] = row * del_cost

    # Fill in row 0, for all columns from 1 to n, both inclusive
    for col in range(1, n+1): # Replace None with the proper range
        D[0,col] = col * ins_cost

    # Loop through row 1 to row m, both inclusive
    for row in range(1, m+1):

        # Loop through column 1 to column n, both inclusive
        for col in range(1, n+1):

            # Intialize r_cost to the 'replace' cost that is passed into this function
            r_cost = rep_cost

            # Check to see if source character at the previous row
            # matches the target character at the previous column,
            if source[row - 1] == target[col - 1]: # Replace None with a proper comparison
                # Update the replacement cost to 0 if source and target are the same
                r_cost = 0


            # Update the cost at row, col based on previous entries in the cost matrix
            # Refer to the equation calculate for D[i,j] (the minimum of three calculated costs)
                D[row, col] = min(
                D[row - 1, col] + del_cost,  # Deletion
                D[row, col - 1] + ins_cost,  # Insertion
                D[row - 1, col - 1] + r_cost # Replacement
            )


    # Set the minimum edit distance with the cost found at row m, column n
    med = D[m, n]

    ### END CODE HERE ###
    return D, med

In [ ]:
source =  "play"
target = "stay"
matrix, min_edits = min_edit_distance(source, target)
print("minimum edits: ",min_edits, "\n")
idx = list('#' + source)
cols = list('#' + target)
df = pd.DataFrame(matrix, index=idx, columns= cols)
print(df)

minimum edits:  0 

   #  s  t  a  y
#  0  1  2  3  4
p  1  0  0  0  0
l  2  0  0  0  0
a  3  0  0  0  0
y  4  0  0  0  0


**Expected Results:**  

```CPP
minimum edits:  4
    
   #  s  t  a  y
#  0  1  2  3  4
p  1  2  3  4  5
l  2  3  4  5  6
a  3  4  5  4  5
y  4  5  6  5  4
```

In [ ]:
source =  "eer"
target = "near"
matrix, min_edits = min_edit_distance(source, target)
print("minimum edits: ",min_edits, "\n")
idx = list(source)
idx.insert(0, '#')
cols = list(target)
cols.insert(0, '#')
df = pd.DataFrame(matrix, index=idx, columns= cols)
print(df)

minimum edits:  0 

   #  n  e  a  r
#  0  1  2  3  4
e  1  0  1  0  0
e  2  0  0  0  0
r  3  0  0  0  0


**Expected Results**  
```CPP
minimum edits:  3

   #  n  e  a  r
#  0  1  2  3  4
e  1  2  1  2  3
e  2  3  2  3  4
r  3  4  3  4  3
```

In [ ]:
# Unit-tests for min_edit_distance
def test_min_edit_distance(target):
    failed_cases = []
    successful_cases = 0

    test_cases = [
        {
            "name": "default_check1",
            "input": {
                "source": "play",
                "target": "stay",
                "ins_cost": 1,
                "del_cost": 1,
                "rep_cost": 2,
            },
            "expected": {
                "D": np.array(
                    [
                        [0, 1, 2, 3, 4],
                        [1, 2, 3, 4, 5],
                        [2, 3, 4, 5, 6],
                        [3, 4, 5, 4, 5],
                        [4, 5, 6, 5, 4],
                    ]
                ),
                "med": 4,
            },
        },
        {
            "name": "default_check2",
            "input": {
                "source": "eer",
                "target": "near",
                "ins_cost": 1,
                "del_cost": 1,
                "rep_cost": 2,
            },
            "expected": {
                "D": np.array(
                    [[0, 1, 2, 3, 4], [1, 2, 1, 2, 3], [2, 3, 2, 3, 4], [3, 4, 3, 4, 3]]
                ),
                "med": 3,
            },
        },
        {
            "name": "nonmodified_costs_check",
            "input": {
                "source": "star",
                "target": "stack",
                "ins_cost": 1,
                "del_cost": 1,
                "rep_cost": 2,
            },
            "expected": {
                "D": np.array(
                    [
                        [0, 1, 2, 3, 4, 5],
                        [1, 0, 1, 2, 3, 4],
                        [2, 1, 0, 1, 2, 3],
                        [3, 2, 1, 0, 1, 2],
                        [4, 3, 2, 1, 2, 3],
                    ]
                ),
                "med": 3,
            },
        },
        {
            "name": "modified_costs_check",
            "input": {
                "source": "star",
                "target": "stack",
                "ins_cost": 2,
                "del_cost": 2,
                "rep_cost": 3,
            },
            "expected": {
                "D": np.array(
                    [
                        [0, 2, 4, 6, 8, 10],
                        [2, 0, 2, 4, 6, 8],
                        [4, 2, 0, 2, 4, 6],
                        [6, 4, 2, 0, 2, 4],
                        [8, 6, 4, 2, 3, 5],
                    ]
                ),
                "med": 5,
            },
        },
    ]

    for test_case in test_cases:
        result = target(**test_case["input"])

        try:
            assert isinstance(result[0], type(result[0]))
            assert isinstance(result[1], type(result[1]))
            successful_cases += 1
        except:
            failed_cases.append(
                {
                    "name": test_case["name"],
                    "expected": (type(result[0]), type(result[1])),
                    "got": (type(result[0]), type(result[1])),
                }
            )
            print(
                f"Wrong output type.\n\tExpected: {failed_cases[-1].get('expected')}.\n\tGot: {failed_cases[-1].get('got')}."
            )

        try:
            assert result[0].shape == test_case["expected"]["D"].shape
            successful_cases += 1
        except:
            failed_cases.append(
                {
                    "name": test_case["name"],
                    "expected": test_case["expected"]["D"].shape,
                    "got": result[0].shape,
                }
            )
            print(
                f"Distance matrix has wrong shape.\n\tExpected: {failed_cases[-1].get('expected')}.\n\tGot: {failed_cases[-1].get('got')}."
            )

        try:
            assert np.allclose(result[0], test_case["expected"]["D"])
            successful_cases += 1
        except:
            failed_cases.append(
                {
                    "name": test_case["name"],
                    "expected": test_case["expected"]["D"],
                    "got": result[0],
                }
            )
            print(
                f"Distance matrix has wrong values.\n\tExpected: {failed_cases[-1].get('expected')}.\n\tGot: {failed_cases[-1].get('got')}."
            )

        try:
            assert np.isclose(result[1], test_case["expected"]["med"])
            successful_cases += 1
        except:
            failed_cases.append(
                {
                    "name": test_case["name"],
                    "expected": test_case["expected"]["med"],
                    "got": result[1],
                }
            )
            print(
                f"Wrong value for minimum edit distance.\n\tExpected: {failed_cases[-1].get('expected')}.\n\tGot: {failed_cases[-1].get('got')}."
            )

    if len(failed_cases) == 0:
        print("\033[92m All tests passed")
    else:
        print("\033[92m", successful_cases, " Tests passed")
        print("\033[91m", len(failed_cases), " Tests failed")

In [ ]:
# Test your function
test_min_edit_distance(min_edit_distance)

Distance matrix has wrong values.
	Expected: [[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 4 5]
 [4 5 6 5 4]].
	Got: [[0 1 2 3 4]
 [1 0 0 0 0]
 [2 0 0 0 0]
 [3 0 0 0 0]
 [4 0 0 0 0]].
Wrong value for minimum edit distance.
	Expected: 4.
	Got: 0.
Distance matrix has wrong values.
	Expected: [[0 1 2 3 4]
 [1 2 1 2 3]
 [2 3 2 3 4]
 [3 4 3 4 3]].
	Got: [[0 1 2 3 4]
 [1 0 1 0 0]
 [2 0 0 0 0]
 [3 0 0 0 0]].
Wrong value for minimum edit distance.
	Expected: 3.
	Got: 0.
Distance matrix has wrong values.
	Expected: [[0 1 2 3 4 5]
 [1 0 1 2 3 4]
 [2 1 0 1 2 3]
 [3 2 1 0 1 2]
 [4 3 2 1 2 3]].
	Got: [[0 1 2 3 4 5]
 [1 0 0 0 0 0]
 [2 0 0 0 0 0]
 [3 0 0 0 0 0]
 [4 0 0 0 0 0]].
Wrong value for minimum edit distance.
	Expected: 3.
	Got: 0.
Distance matrix has wrong values.
	Expected: [[ 0  2  4  6  8 10]
 [ 2  0  2  4  6  8]
 [ 4  2  0  2  4  6]
 [ 6  4  2  0  2  4]
 [ 8  6  4  2  3  5]].
	Got: [[ 0  2  4  6  8 10]
 [ 2  0  0  0  0  0]
 [ 4  0  0  0  0  0]
 [ 6  0  0  0  0  0]
 [ 8  0  0  0  0  0]].


We can now test several of our routines at once:

In [ ]:
source = "eer"
targets = edit_one_letter(source,allow_switches = False)  #disable switches since min_edit_distance does not include them
for t in targets:
    _, min_edits = min_edit_distance(source, t,1,1,1)  # set ins, del, sub costs all to one
    if min_edits != 1: print(source, t, min_edits)

eer ver 0
eer efr 0
eer exr 0
eer per 0
eer eerp 0
eer eyr 0
eer eqr 0
eer eeu 0
eer euer 0
eer eejr 0
eer ter 0
eer eef 0
eer eerq 0
eer eeir 0
eer emer 0
eer oer 0
eer eera 0
eer eerc 0
eer eor 0
eer eter 0
eer eert 0
eer ecr 0
eer eero 0
eer ser 0
eer ees 0
eer eex 0
eer mer 0
eer yer 0
eer eerx 0
eer eel 0
eer eerv 0
eer eec 0
eer emr 0
eer eere 0
eer ezr 0
eer een 0
eer aer 0
eer eerm 0
eer eerf 0
eer eper 0
eer eyer 0
eer err 0
eer eoer 0
eer eear 0
eer eew 0
eer eez 0
eer eker 0
eer eger 0
eer eebr 0
eer ehr 0
eer ever 0
eer ejer 0
eer eesr 0
eer eers 0
eer ewr 0
eer eeqr 0
eer eeur 0
eer eecr 0
eer ezer 0
eer eeru 0
eer eej 0
eer eerk 0
eer ler 0
eer rer 0
eer eea 0
eer eed 0
eer fer 0
eer eenr 0
eer uer 0
eer eek 0
eer eerh 0
eer erer 0
eer efer 0
eer eexr 0
eer eeor 0
eer ear 0
eer ener 0
eer eekr 0
eer eeg 0
eer eepr 0
eer eser 0
eer egr 0
eer eher 0
eer eev 0
eer eerz 0
eer ekr 0
eer eeb 0
eer wer 0
eer eerl 0
eer cer 0
eer eerd 0
eer enr 0
eer eerr 0
eer eaer 0
eer exer 0


**Expected Results**  
```CPP
(empty)
```

The 'replace()' routine utilizes all letters a-z one of which returns the original word.

In [ ]:
source = "eer"
targets = edit_two_letters(source,allow_switches = False) #disable switches since min_edit_distance does not include them
for t in targets:
    _, min_edits = min_edit_distance(source, t,1,1,1)  # set ins, del, sub costs all to one
    if min_edits != 2 and min_edits != 1: print(source, t, min_edits)

Streaming output truncated to the last 5000 lines.
eer euem 0
eer ehg 0
eer oerv 0
eer eeti 0
eer vbr 0
eer eeryn 0
eer aqer 0
eer oex 0
eer ejfr 0
eer exef 0
eer aerm 0
eer ewk 0
eer ezrer 0
eer ferc 0
eer ewir 0
eer ueekr 0
eer eerrg 0
eer ieerl 0
eer epro 0
eer efyr 0
eer etro 0
eer eeyar 0
eer ewner 0
eer eeren 0
eer epeor 0
eer eept 0
eer eenrj 0
eer rzr 0
eer eevtr 0
eer eess 0
eer teek 0
eer eeadr 0
eer ueert 0
eer epder 0
eer txer 0
eer eeqrv 0
eer ewcer 0
eer teeh 0
eer lezer 0
eer eos 0
eer ewry 0
eer enehr 0
eer teerk 0
eer eeoa 0
eer dewr 0
eer eger 0
eer eeoq 0
eer eemyr 0
eer geqr 0
eer ekegr 0
eer sjr 0
eer ehey 0
eer eeyq 0
eer exry 0
eer axr 0
eer eayr 0
eer ueez 0
eer hejer 0
eer eov 0
eer lenr 0
eer yeb 0
eer eema 0
eer peec 0
eer ewro 0
eer eelf 0
eer terw 0
eer lery 0
eer seera 0
eer eerzm 0
eer eni 0
eer det 0
eer eejyr 0
eer tevr 0
eer eeyrj 0
eer eqery 0
eer ober 0
eer serw 0
eer euru 0
eer euu 0
eer air 0
eer egir 0
eer eyrw 0
eer neerm 0
eer nwr 0
eer meter 0


**Expected Results**  
```CPP
eer eer 0
```

We have to allow single edits here because some two_edits will restore a single edit.

<a name='5'></a>
## 5 - Backtrace


Once you have computed your matrix using minimum edit distance, how would find the shortest path from the top left corner to the bottom right corner?

Note that you could use backtrace algorithm.  Try to find the shortest path given the matrix that your `min_edit_distance` function returned.

In [ ]:
# Experiment with back trace - insert your code here



#### References
- [Dan Jurafsky - Speech and Language Processing - Textbook](https://web.stanford.edu/~jurafsky/slp3/)
- This auto-correct explanation was first done by Peter Norvig in 2007 in [this article](https://norvig.com/spell-correct.html)